### ISSUE TITLE
使用reload plugin命令热重载JS插件报错

### ISSUE THREAD

**Issue by CoolLoong** [PowerNukkitX/PowerNukkitX#1030]
# 🐞 错误汇报

使用reload plugin热重载一个依赖其他JS插件的JS插件，会导致被依赖的JS插件在服务器关闭时报错。
### 💢 错误堆栈或崩溃日志

```
org.graalvm.polyglot.PolyglotException: The Context is already closed.
	at com.oracle.truffle.polyglot.PolyglotEngineException.closedException(PolyglotEngineException.java:139) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.polyglot.PolyglotContextImpl.checkClosedOrDisposing(PolyglotContextImpl.java:1257) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.polyglot.PolyglotContextImpl.enterThreadChanged(PolyglotContextImpl.java:808) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.enterCached(PolyglotEngineImpl.java:2039) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:109) ~[org.graalvm.truffle:?]
	at org.graalvm.polyglot.Value.getMetaQualifiedName(Value.java:234) ~[org.graalvm.sdk:?]
	at cn.nukkit.plugin.js.JSExternal.checkAlive(JSExternal.java:15) ~[powernukkitx-1.19.60-r1.jar:?]
	at cn.nukkit.plugin.js.external.ExternalObject.hasMember(ExternalObject.java:33) ~[powernukkitx-1.19.60-r1.jar:?]
	at <js>.close(@LiteLoaderLibs/index.js:10) ~[?:?]
	at org.graalvm.polyglot.Value.executeVoid(Value.java:900) ~[org.graalvm.sdk:?]
	at cn.nukkit.plugin.CommonJSPlugin.onDisable(CommonJSPlugin.java:151) ~[powernukkitx-1.19.60-r1.jar:?]
	at cn.nukkit.plugin.JSPluginLoader.disablePlugin(JSPluginLoader.java:79) ~[powernukkitx-1.19.60-r1.jar:?]
	at cn.nukkit.plugin.PluginManager.disablePlugin(PluginManager.java:547) [powernukkitx-1.19.60-r1.jar:?]
	at cn.nukkit.plugin.PluginManager.disablePlugins(PluginManager.java:535) [powernukkitx-1.19.60-r1.jar:?]
	at cn.nukkit.Server.forceShutdown(Server.java:1322) [powernukkitx-1.19.60-r1.jar:?]
	at cn.nukkit.Server.start(Server.java:1398) [powernukkitx-1.19.60-r1.jar:?]
	at cn.nukkit.Server.<init>(Server.java:948) [powernukkitx-1.19.60-r1.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:160) [powernukkitx-1.19.60-r1.jar:?]
```

**Comment by Superice666** [comment]
有最小可复现插件示例吗
