### ISSUE TITLE
pnx-js 在抽象其它插件的class时出现越权错误

### ISSUE THREAD

**Issue by Mcayear** [PowerNukkitX/PowerNukkitX#1130]
# 🐞 错误汇报

代码参考：
https://gist.github.com/Mcayear/b8a86965113bbb50c4c7933d8224412f#file-index-js-L329

FakeInventoryListener：
https://github.com/CloudburstMC/FakeInventories/blob/master/src/main/java/com/nukkitx/fakeinventories/inventory/FakeInventoryListener.java

错误信息：
```
09:23:45 [INFO ] [NInvShop]: func 3
09:23:45 [INFO ] 在执行此指令时出现了未知的错误
> 2023-04-09 09:23:45,609 main ERROR An exception occurred processing Appender Sentry org.apache.logging.log4j.core.appender.AppenderLoggingException: java.lang.IllegalAccessError: superclass access check failed: class com.oracle.truffle.js.runtime.JavaScriptRootNode (in unnamed module @0x77847718) cannot access class com.oracle.truffle.api.nodes.RootNode (in module org.graalvm.truffle) because module org.graalvm.truffle does not export com.oracle.truffle.api.nodes to unnamed module @0x77847718
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:165)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
        at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2017)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1983)
        at org.apache.logging.log4j.spi.AbstractLogger.fatal(AbstractLogger.java:1063)
        at cn.nukkit.command.SimpleCommandMap.executeCommand(SimpleCommandMap.java:336)
        at cn.nukkit.Server.executeCommand(Server.java:1222)
        at cn.nukkit.Server.dispatchCommand(Server.java:1193)
        at com.smallaswater.npc.utils.Utils.executeCommand(Utils.java:66)
        at com.smallaswater.npc.utils.Utils.executeCommand(Utils.java:47)
        at com.smallaswater.npc.OnListener.onDamage(OnListener.java:73)
        at cn.nukkit.plugin.PNXMethodEventExecutor$49.execute(EventHandler@com.smallaswater.npc.OnListener#onDamage)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:61)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:580)
        at cn.nukkit.entity.Entity.attack(Entity.java:1815)
        at cn.nukkit.entity.EntityLiving.attack(EntityLiving.java:119)
        at cn.nukkit.entity.EntityHumanType.attack(EntityHumanType.java:97)
        at cn.nukkit.Player.handleDataPacket(Player.java:5330)
        at cn.nukkit.network.session.RakNetPlayerSession.serverTick(RakNetPlayerSession.java:180)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:96)
        at cn.nukkit.network.Network.processInterfaces(Network.java:236)
        at cn.nukkit.Server.tick(Server.java:1761)
        at cn.nukkit.Server.tickProcessor(Server.java:1490)
        at cn.nukkit.Server.start(Server.java:1450)
        at cn.nukkit.Server.<init>(Server.java:954)
        at cn.nukkit.Nukkit.main(Nukkit.java:160)
```

### 💬 其他信息
plugin.yml
```
name: NInvShop
main: index.js # JS入口文件，应该导出一个main函数（如main.js）
version: "0.0.1"
api: [ "1.0.13" ] # API版本，PNX从1.0.13起开始支持JS插件
load: POSTWORLD # 插件加载顺序，只能填写 STARTUP 或 POSTWORLD
# STARTUP: 此时服务器刚启动，地图尚未加载，通常用于依赖库
# POSTWORLD: 此时服务器所有地图都加载完毕，通常填写POSTWORLD即可
authors: # 此项可以不存在
  - Mcayear
description: 年的商店插件
website: https://mc.xz.cn
features: []
depend: # 插件的依赖项
- NJSUtil
- LLSELib
- FakeInventories
softdepend: # 插件的软依赖项
- NWeaponRe
features:
  - WsClient
```
插件：
```
> plugins
09:27:45 [INFO ] 插件 (23)：PowerNukkitX v1.19.70-r2, ScoreboardPlugin v1.0, MagicItem v1.0.1, NJSUtil v1.0.0, HealthAPI v1.3.2, Tips v2.1.0, LittleMonster v1.7.0-SNAPSHOT, EconomyEvent v1.0.1, CloseCheckMovement v1.0-SNAPSHOT, Knickers v2.2.3, SetJoinQuitMessage v1.0.5, NoSpaceInName v1.1.0, FakeInventories v1.0.4, EssentialsNK v1.9.2, TipsVeriable v1.0.0, EconomyAPI v2.0.2, LLSELib v0.0.5, MemoriesOfTime-GameCore v1.6.8.0-PNX, RsNPC v2.3.1-PNX, NWeaponRe v0.0.1, AyearTipsApi v1.0.0, NTitle v0.0.1, NInvShop v0.0.1
```
服务器版本：
```
> version
09:27:48 [INFO ] 此服务器正在运行 Nukkit 1.19.70-r2 (git-908d32fbf) 「PowerNukkitX」API 版本 1.0.14 的 Minecraft: BE v1.19.70 (协议版本 575)
```

**Comment by Superice666** [comment]
GraalJS的松露系统不支持此写法，请在上游[Graal](https://github.com/oracle/graal)中提出建议
