### ISSUE TITLE
Unable to debug Java plugin with IntelliJ IDEA

### ISSUE THREAD

**Issue by Bestaford** [PowerNukkitX/PowerNukkitX#1143]
An exception is raised when attempting to debug:

```
Exception in thread "main" joptsimple.MultipleArgumentsForOptionException: Found multiple arguments for option js-debug, but you asked for only one
	at joptsimple.OptionSet.valueOf(OptionSet.java:179)
	at cn.nukkit.Nukkit.main(Nukkit.java:153)
```

Run/debug configuration file:

```
<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="Run (work)" type="JarApplication">
    <option name="JAR_PATH" value="$PROJECT_DIR$/../../PNX/powernukkitx.jar" />
    <option name="VM_PARAMETERS" value="-Dfile.encoding=UTF-8 -Djansi.passthrough=true -Dterminal.ansi=true -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+EnableJVMCI --module-path=./libs/truffle-api-22.2.0.jar:./libs/graal-sdk-22.2.0.jar: --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED -cp ./powernukkitx.jar:./libs/*:./plugins/*: cn.nukkit.Nukkit" />
    <option name="WORKING_DIRECTORY" value="$PROJECT_DIR$/../../PNX" />
    <option name="ALTERNATIVE_JRE_PATH" value="temurin-17" />
    <method v="2">
      <option name="RunConfigurationTask" enabled="true" run_configuration_name="Build" run_configuration_type="MavenRunConfiguration" />
    </method>
  </configuration>
</component>
```

IDEA`s command line for debug:
```
/usr/lib64/jvm/temurin-17-jdk/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:44323,suspend=y,server=n -Dfile.encoding=UTF-8 -Djansi.passthrough=true -Dterminal.ansi=true -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+EnableJVMCI --module-path=./libs/truffle-api-22.2.0.jar:./libs/graal-sdk-22.2.0.jar: --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED -cp ./powernukkitx.jar:./libs/*:./plugins/*: cn.nukkit.Nukkit -javaagent:/home/bestaford/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/231.8109.175/plugins/java/lib/rt/debugger-agent.jar=file:/tmp/capture9.props -jar /home/bestaford/Документы/PNX/powernukkitx.jar
```

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/59061055/233937774-fc8bccbf-675d-4894-95bb-4ccee2b2134f.png)

![image](https://user-images.githubusercontent.com/59061055/233938275-26325db1-af12-4bdb-a7b1-c9968271521b.png)

</details>

**Comment by CoolLoong** [comment]
refer: run config
https://github.com/PowerNukkitX/ExamplePlugin-Maven/blob/master/.run/PNX.run.xml
