### ISSUE TITLE
卸载区块时发生错误

### ISSUE THREAD

**Issue by szzz666** [PowerNukkitX/PowerNukkitX#1281]
# 🐞 错误汇报

报错 [ERROR] 卸载区块时发生错误
### 📸 截图或视频

![image](https://github.com/PowerNukkitX/PowerNukkitX/assets/60167194/60baec81-3502-4d27-a4fd-023da3c36907)

### ▶ 复现步骤

不清是什么原因
个人推测可能是
1.服务器断电
2.之前安装了科技黎明使用了里面的方块然后又删除了

### ✔ 预期行为

没有报错

### ❌ 实际行为

报错了

### 📋 Debug information

[debugpaste-2023-07-02T15.30.33.172+0800.zip](https://github.com/PowerNukkitX/PowerNukkitX/files/11928916/debugpaste-2023-07-02T15.30.33.172%2B0800.zip)
[20230702153153_NullPointerException.md](https://github.com/PowerNukkitX/PowerNukkitX/files/11928918/20230702153153_NullPointerException.md)

### 💢 错误堆栈或崩溃日志

15:26:47 [ERROR] 卸载区块时发生错误：cn.nukkit.utils.ChunkException: Error saving chunk (32, -85)
cn.nukkit.utils.ChunkException: Error saving chunk (32, -85)
        at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:358) ~[powernukkitx.jar:?]
        at cn.nukkit.level.Level.unloadChunk(Level.java:4237) [powernukkitx.jar:?]
        at cn.nukkit.level.Level.unloadChunk(Level.java:4198) [powernukkitx.jar:?]
        at cn.nukkit.level.Level.unloadChunks(Level.java:4662) [powernukkitx.jar:?]
        at cn.nukkit.level.Level.doGarbageCollection(Level.java:4562) [powernukkitx.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:1165) [powernukkitx.jar:?]
        at cn.nukkit.Server.start(Server.java:1133) [powernukkitx.jar:?]
        at cn.nukkit.Server.<init>(Server.java:960) [powernukkitx.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:160) [powernukkitx.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "cn.nukkit.block.customblock.CustomBlock.getNamespaceId()" because the return value of "it.unimi.dsi.fastutil.ints.Int2ObjectMap.get(int)" is null
        at cn.nukkit.level.format.anvil.ChunkSection.toNBT(ChunkSection.java:899) ~[powernukkitx.jar:?]
        at cn.nukkit.level.format.anvil.Chunk.toBinary(Chunk.java:529) ~[powernukkitx.jar:?]
        at cn.nukkit.level.format.anvil.RegionLoader.writeChunk(RegionLoader.java:172) ~[powernukkitx.jar:?]
        at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:356) ~[powernukkitx.jar:?]
        ... 8 more

**Comment by SuperIceCN** [comment]
这是由于地图中残留了已卸载模组的自定义方块造成的，可以重新安装模组后清理掉它们。  
理论上PNX应该会发出警告并跳过此方块，造成报错的原因需要进一步分析。

**Comment by szzz666** [comment]
等你们修好~

**Comment by szzz666** [comment]
修复后报错减少了并且变成在“保存地图时发现了未知的自定义方块，id=1050。”
但是还是有漏网之鱼，比如下面这个报错
17:02:40 [ERROR] 更新世界 "茅亭之境" 时出现错误：java.lang.NullPointerException: Cannot invoke "cn.nukkit.block.customblock.CustomBlock.toCustomBlock()" because the return value of "it.unimi.dsi.fastutil.ints.Int2ObjectMap.get(int)" is null
        at cn.nukkit.block.Block.get(Block.java:952)
        at cn.nukkit.blockstate.IBlockState.getBlock(IBlockState.java:292)
        at cn.nukkit.blockstate.BlockState.getBlock(BlockState.java:732)
        at cn.nukkit.blockstate.IBlockState.getBlock(IBlockState.java:272)
        at cn.nukkit.level.Level.getBlock(Level.java:2364)
        at cn.nukkit.level.Level.getBlock(Level.java:2322)
        at cn.nukkit.level.Level.getBlock(Level.java:2317)
        at cn.nukkit.level.Level.getCollisionBlocks(Level.java:1961)
        at cn.nukkit.level.Level.getCollisionBlocks(Level.java:1932)
        at cn.nukkit.level.Level.getCollisionBlocks(Level.java:1927)
        at cn.nukkit.level.Level.getCollisionBlocks(Level.java:1923)
        at cn.nukkit.Player.fastMove(Player.java:3089)
        at cn.nukkit.Player.handleMovement(Player.java:1112)
        at cn.nukkit.Player.onUpdate(Player.java:3225)
        at cn.nukkit.level.Level.doTick(Level.java:1260)
        at cn.nukkit.Server.checkTickUpdates(Server.java:1203)
        at cn.nukkit.Server.tick(Server.java:1289)
        at cn.nukkit.Server.tickProcessor(Server.java:1152)
        at cn.nukkit.Server.start(Server.java:1133)
        at cn.nukkit.Server.<init>(Server.java:960)
        at cn.nukkit.Nukkit.main(Nukkit.java:160)

java.lang.NullPointerException: Cannot invoke "cn.nukkit.block.customblock.CustomBlock.toCustomBlock()" because the return value of "it.unimi.dsi.fastutil.ints.Int2ObjectMap.get(int)" is null
        at cn.nukkit.block.Block.get(Block.java:952) ~[powernukkitx.jar:?]
        at cn.nukkit.blockstate.IBlockState.getBlock(IBlockState.java:292) ~[powernukkitx.jar:?]
        at cn.nukkit.blockstate.BlockState.getBlock(BlockState.java:732) ~[powernukkitx.jar:?]
        at cn.nukkit.blockstate.IBlockState.getBlock(IBlockState.java:272) ~[powernukkitx.jar:?]
        at cn.nukkit.level.Level.getBlock(Level.java:2364) ~[powernukkitx.jar:?]
        at cn.nukkit.level.Level.getBlock(Level.java:2322) ~[powernukkitx.jar:?]
        at cn.nukkit.level.Level.getBlock(Level.java:2317) ~[powernukkitx.jar:?]
        at cn.nukkit.level.Level.getCollisionBlocks(Level.java:1961) ~[powernukkitx.jar:?]
        at cn.nukkit.level.Level.getCollisionBlocks(Level.java:1932) ~[powernukkitx.jar:?]
        at cn.nukkit.level.Level.getCollisionBlocks(Level.java:1927) ~[powernukkitx.jar:?]
        at cn.nukkit.level.Level.getCollisionBlocks(Level.java:1923) ~[powernukkitx.jar:?]
        at cn.nukkit.Player.fastMove(Player.java:3089) ~[powernukkitx.jar:?]
        at cn.nukkit.Player.handleMovement(Player.java:1112) ~[powernukkitx.jar:?]
        at cn.nukkit.Player.onUpdate(Player.java:3225) ~[powernukkitx.jar:?]
        at cn.nukkit.level.Level.doTick(Level.java:1260) ~[powernukkitx.jar:?]
        at cn.nukkit.Server.checkTickUpdates(Server.java:1203) [powernukkitx.jar:?]
        at cn.nukkit.Server.tick(Server.java:1289) [powernukkitx.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:1152) [powernukkitx.jar:?]
        at cn.nukkit.Server.start(Server.java:1133) [powernukkitx.jar:?]
        at cn.nukkit.Server.<init>(Server.java:960) [powernukkitx.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:160) [powernukkitx.jar:?]

还有这个
 [ERROR] 卸载区块时发生错误：cn.nukkit.utils.ChunkException: Error saving chunk (71, -80)
cn.nukkit.utils.ChunkException: Error saving chunk (71, -80)
        at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:358) ~[powernukkitx.jar:?]
        at cn.nukkit.level.Level.unloadChunk(Level.java:4237) ~[powernukkitx.jar:?]
        at cn.nukkit.level.Level.unloadChunk(Level.java:4198) ~[powernukkitx.jar:?]
        at cn.nukkit.level.Level.unloadChunks(Level.java:4608) ~[powernukkitx.jar:?]
        at cn.nukkit.level.Level.unloadChunks(Level.java:4573) ~[powernukkitx.jar:?]
        at cn.nukkit.level.Level.unloadChunks(Level.java:4569) ~[powernukkitx.jar:?]
        at cn.nukkit.level.Level.lambda$asyncChunkGarbageCollection$26(Level.java:4493) ~[powernukkitx.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1630) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1628) ~[?:?]
        at cn.nukkit.scheduler.BlockUpdateScheduler.getPendingBlockUpdates(BlockUpdateScheduler.java:79) ~[powernukkitx.jar:?]
        at cn.nukkit.level.Level.getPendingBlockUpdates(Level.java:1904) ~[powernukkitx.jar:?]
        at cn.nukkit.level.Level.getPendingBlockUpdates(Level.java:1900) ~[powernukkitx.jar:?]
        at cn.nukkit.level.format.anvil.Chunk.toBinary(Chunk.java:565) ~[powernukkitx.jar:?]
        at cn.nukkit.level.format.anvil.RegionLoader.writeChunk(RegionLoader.java:172) ~[powernukkitx.jar:?]
        at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:356) ~[powernukkitx.jar:?]
        ... 13 more

**Comment by SuperIceCN** [comment]
这是不同的错误，此错误是由于玩家与未注册的自定义方块交互产生的，请清理地图中的自定义方块

**Comment by szzz666** [comment]
能不能加一个自动清理，毕竟太多了，而且我也不知道方块在哪里，谢谢你中国超级冰
