### ISSUE TITLE
java.lang.IllegalArgumentException: Could not find option with name js.esm-eval-returns-exports.

### ISSUE THREAD

**Issue by Mcayear** [PowerNukkitX/PowerNukkitX#1362]
# 🐞 错误汇报

### JS插件无法加载。

```txt
13:59:16 [INFO ] 读取 LLSELib v0.0.5 中
13:59:16 [FATAL] Could not load plugin
java.lang.IllegalArgumentException: Could not find option with name js.esm-eval-returns-exports.
        at com.oracle.truffle.polyglot.PolyglotEngineException.illegalArgument(PolyglotEngineException.java:131) ~[org.graalvm.truffle:?]
        at com.oracle.truffle.polyglot.OptionValuesImpl.failNotFound(OptionValuesImpl.java:288) ~[org.graalvm.truffle:?]
        at com.oracle.truffle.polyglot.PolyglotEngineImpl.parseOptions(PolyglotEngineImpl.java:763) ~[org.graalvm.truffle:?]
        at com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:322) ~[org.graalvm.truffle:?]
        at com.oracle.truffle.polyglot.PolyglotImpl.buildEngine(PolyglotImpl.java:283) ~[org.graalvm.truffle:?]
        at com.oracle.truffle.polyglot.enterprise.EnterprisePolyglotImpl.buildEngine(stripped:136) ~[com.oracle.graal.graal_enterprise:?]
        at org.graalvm.polyglot.Engine$Builder.build(Engine.java:681) ~[org.graalvm.sdk:?]
        at org.graalvm.polyglot.Context$Builder.build(Context.java:1926) ~[org.graalvm.sdk:?]
        at cn.nukkit.plugin.CommonJSPlugin.init(CommonJSPlugin.java:95) ~[powernukkitx.jar:?]
        at cn.nukkit.plugin.JSPluginLoader.loadPlugin(JSPluginLoader.java:39) ~[powernukkitx.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:124) [powernukkitx.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:313) [powernukkitx.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:161) [powernukkitx.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:153) [powernukkitx.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:149) [powernukkitx.jar:?]
        at cn.nukkit.Server.<init>(Server.java:867) [powernukkitx.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:160) [powernukkitx.jar:?]
13:59:16 [FATAL] 无法读取插件 "LLSELib"
```
![image](https://github.com/PowerNukkitX/PowerNukkitX/assets/48203962/b7dec6ef-9634-4c24-93db-0b22cf799fc2)

### 版本
PowerNukkitX 1.20.10-r1
```
> version
14:01:53 [INFO ] 此服务器正在运行 Nukkit 1.20.10-r1 (git-c35d320d4) 「PowerNukkitX」API 版本 1.0.14 的 Minecraft: BE v1.20.10 (协议版本 594)
```

**Comment by Mcayear** [comment]
原因同 https://github.com/PowerNukkitX/PowerNukkitX/issues/993 

解决方法：
使用 `"./java/graalvm-jdk-20.0.2+9.1/bin/gu" install js`安装javascript组件即可
![image](https://github.com/PowerNukkitX/PowerNukkitX/assets/48203962/ee3a8819-1929-4f46-a886-a0760ac1fe35)
