### ISSUE TITLE
PNX最新Commit版本的方块注册问题

### ISSUE THREAD

**Issue by PengLx** [PowerNukkitX/PowerNukkitX#1373]
# 🐞 错误汇报
无法注册自定义方块
### 💢 错误堆栈或崩溃日志

```
2023-09-08 16:13:09.128 [main] ERROR - Catching
java.lang.Error: Unresolved compilation problems: 
	The method getNamespaceId() is undefined for the type Object
	The method getNamespaceId() is undefined for the type Object
	The method getId() is undefined for the type Object
	The method getId() is undefined for the type Object
	The method getId() is undefined for the type Object
	The method getName() is undefined for the type Object
	The method getName() is undefined for the type Object
	The method getName() is undefined for the type Object
	The method getName() is undefined for the type Object
	length cannot be resolved or is not a field
	The method getName() is undefined for the type Object
	The method getName() is undefined for the type Object
	The method copy() is undefined for the type Object
	The method getName() is undefined for the type Object
	The method copy() is undefined for the type Object
	The method getName() is undefined for the type Object
	The method copy() is undefined for the type Object
	The method getName() is undefined for the type Object
	The method copy() is undefined for the type Object
	The method getName() is undefined for the type Object
	length cannot be resolved or is not a field
	The method copy() is undefined for the type Object
	The method getName() is undefined for the type Object
	The method copy() is undefined for the type Object
	The method getName() is undefined for the type Object
	The method putCompound(String, CompoundTag) in the type CompoundTag is not applicable for the arguments (String, Object)
	The method getNamespaceId() is undefined for the type Object
	The method getNamespaceId() is undefined for the type Object
	The method putInt(String, int) is undefined for the type Object
	The method add(CompoundTag) in the type List<CompoundTag> is not applicable for the arguments (Object)
	The method getInt(String) is undefined for the type Object
	The method getString(String) is undefined for the type Object
	The method registerStateId(CompoundTag, int) in the type BlockStateRegistry is not applicable for the arguments (Object, int)
	The method registerStateId(CompoundTag, int) in the type BlockStateRegistry is not applicable for the arguments (Object, int)

	at cn.nukkit.blockstate.BlockStateRegistry.registerCustomBlockState(BlockStateRegistry.java:542) ~[pnx.jar:?]
	at cn.nukkit.block.Block.initCustomBlock(Block.java:1363) ~[pnx.jar:?]
	at cn.nukkit.Server.<init>(Server.java:868) ~[pnx.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:160) [pnx.jar:?]
```

**Comment by lt-name** [comment]
你写的方块类的getNamespaceId()方法返回值不对

**Comment by lt-name** [comment]
另外建议提供你写的注册代码部分截图，以及详细的pnx版本号

**Comment by PengLx** [comment]
```
@AutoRegister
class BalloonCrate : StandardBlock() {
    override fun getNamespaceId(): String {
        return "starsserverdecoration:balloon_crate"
    }

    override fun getMaterial(): Materials {
        return Materials.builder()
            .up(Materials.RenderMethod.OPAQUE,"starsserverdecoration-balloon_crate_top")
            .down(Materials.RenderMethod.OPAQUE, "starsserverdecoration-balloon_crate_top")
            .any(Materials.RenderMethod.OPAQUE, "starsserverdecoration-balloon_crate_side")
    }
}

```
    private fun registerCustomBlock(clazz: Class<*>) {
        if(TabooLibCommon.isDevelopmentMode()) {
            dev("Register custom block ${clazz.simpleName}")
        }
        Block.registerCustomBlock(listOf(clazz.castToType<CustomBlock>()))
    }
```
    private fun scanClasses(className: String) {
        try {
            val clazz = Class.forName(className)
            val modifiers = clazz.modifiers

            if (Modifier.isAbstract(modifiers) || !clazz.isAnnotationPresent(AutoRegister::class.java)) {
                return
            }

            if(TabooLibCommon.isDevelopmentMode()) {
                dev("Scanned target class ${clazz.simpleName}")
            }

            when {
                isTypeOf<CustomItem>(clazz) -> registerCustomItem(clazz)
                isTypeOf<BlockEntity>(clazz) -> registerBlockEntity(clazz)
                isTypeOf<CustomBlock>(clazz) -> registerCustomBlock(clazz)
                isTypeOf<Enchantment>(clazz) -> registerEnchantment(clazz)
                isTypeOf<Entity>(clazz) -> registerEntity(clazz)
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
```

**Comment by PengLx** [comment]
> 你写的方块类的getNamespaceId()方法返回值不对

我用了之前的旧版测试没有任何问题，是可以注册上的。无论是我的AutoRegister还是 普通的方法直接注册。

新版就是最新的Commit的Build构建测试的

**Comment by PengLx** [comment]
```
abstract public class StandardBlock extends Block implements CustomBlock, CreativeCategory {
    @Override
    public String getName() {
        return CustomBlock.super.getName();
    }

    @Override
    public int getId() {
        return CustomBlock.super.getId();
    }

    abstract public Materials getMaterial();

    @Override
    public BlockCreativeCategory getBlockCreativeCategory() {
        return BlockCreativeCategory.NONE;
    }

    @Override
    public ItemCreativeGroup getItemCreativeGroup() {
        return ItemCreativeGroup.NONE;
    }

    @Override
    public CustomBlockDefinition getDefinition() {
        return CustomBlockDefinition
                .builder(this, getMaterial(), getBlockCreativeCategory())
                .creativeGroup(getItemCreativeGroup())
                .build();
    }
}

```

**Comment by PengLx** [comment]
> 另外建议提供你写的注册代码部分截图，以及详细的pnx版本号

99bff6f90c543987bb23cd675ad33934a5cd4bec

**Comment by lt-name** [comment]
更新插件编译的依赖，运行时环境的pnx重新下载下，看起来像是缺东西
