### ISSUE TITLE
Error after upgrading 1.20.50-r1

### ISSUE THREAD

**Issue by eat-sleep-code** [PowerNukkitX/PowerNukkitX#1478]
I upgraded to 1.20.50-r1, and now I receive the following error.   This was not occurring before 1.20.50-r1.

```
05:00:11 [INFO ] Using JVM: Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 20.0.2+9.11
05:00:11 [INFO ] Using PNX core: 1.20.50-r1 - 777d7b32a1
05:00:12 [INFO ] Loading nukkit.yml ...
05:00:12 [INFO ] Loading server.properties ...
05:00:12 [INFO ] Selected English (eng) as the base language
05:00:12 [INFO ] Starting Minecraft: BE server version v1.20.50
05:00:12 [WARN ] Hardware (de)compression acceleration is still experimental! If you find any issue, please report them at github.
05:00:12 [INFO ] Selected Zlib provider: 3 (cn.nukkit.utils.LibDeflateThreadLocal)
05:00:12 [INFO ] Opening server on 0.0.0.0:19132
05:00:13 [INFO ] This server is running Nukkit version 1.20.50-r1 (git-777d7b32a) "PowerNukkitX" (API 1.0.14)
05:00:13 [INFO ] Nukkit is distributed under the GPL License
05:00:13 [INFO ] Loading runtime items...
05:00:14 [INFO ] Loading recipes...
05:00:15 [INFO ] Loaded 2263 recipes.
05:00:15 [INFO ] Resource pack loaded successfully: "Vanilla-RTX-v2.5.1.mcpack"
05:00:15 [INFO ] Resource pack loaded successfully: "Vanilla-RTX-smooth-quartz-addon-v2.5.mcpack"
05:00:15 [INFO ] Resource pack loaded successfully: "Vanilla-RTX-3d-stone-addon-v2.5.mcpack"
05:00:15 [INFO ] Resource pack loaded successfully: "Vanilla-RTX-textured-water-addon-v2.5.mcpack"
05:00:15 [INFO ] Resource pack loaded successfully: "Vanilla-RTX-clear-glass-addon-v2.5.mcpack"
05:00:15 [INFO ] Successfully loaded 5 resource packs
05:00:15 [INFO ] Enabling PowerNukkitX v1.20.50-r1
05:00:15 [INFO ] Loading EssentialsNK v1.9.2
05:00:15 [INFO ] Loading NPC v2.7.0
05:00:15 [INFO ] Loading Pets v1.6.4
05:00:15 [INFO ] Loading MobPlugin v1.25.2
05:00:15 [INFO ] Loading WorldEssentials v2.4.0
05:00:15 [INFO ] Loading Residence v1.3.8
05:00:15 [INFO ] Enabling NPC v2.7.0
05:00:15 [INFO ] Enabling MobPlugin v1.25.2
05:00:15 [WARN ] [MobPlugin]: MobPlugin does not support unofficial Nukkit versions!
05:00:15 [INFO ] Initializing Terra...
05:00:15 [INFO ] Loading config.yml
05:00:15 [INFO ] Loading config values from config.yml
05:00:15 [INFO ] Loading 34 Terra addons:
        - biome-provider-extrusion@1.0.0-BETA+358e09d05
        - biome-provider-image@1.0.0-BETA+358e09d05
        - biome-provider-image-v2@1.0.0-BETA+0be7213ee
        - biome-provider-pipeline@1.0.1-BETA+358e09d05
        - biome-provider-pipeline-v2@1.0.0-BETA+358e09d05
        - biome-provider-single@1.0.0-BETA+358e09d05
        - biome-query-api@1.0.0-BETA+358e09d05
        - chunk-generator-noise-3d@1.1.0-BETA+358e09d05
        - command-addons@1.0.0-BETA+358e09d05
        - command-packs@1.0.0-BETA+358e09d05
        - command-profiler@1.0.0-BETA+358e09d05
        - command-structures@1.0.0-BETA+358e09d05
        - config-biome@1.0.0-BETA+358e09d05
        - config-distributors@1.0.0-BETA+358e09d05
        - config-feature@1.0.0-BETA+358e09d05
        - config-flora@1.0.0-BETA+358e09d05
        - config-locators@1.1.0-BETA+358e09d05
        - config-noise-function@1.0.0-BETA+358e09d05
        - config-ore@1.0.0-BETA+358e09d05
        - config-palette@1.0.0-BETA+358e09d05
        - config-structure@1.0.0-BETA+358e09d05
        - generation-stage-feature@1.1.0-BETA+358e09d05
        - generation-stage-structure@1.0.0-BETA+358e09d05
        - language-yaml@1.0.0-BETA+358e09d05
        - library-image@1.0.0-BETA+0be7213ee
        - palette-block-shortcut@1.0.0-BETA+358e09d05
        - pipeline-image@1.0.0-BETA+0be7213ee
        - structure-block-shortcut@1.0.0-BETA+358e09d05
        - structure-function-check-noise-3d@1.0.0-BETA+358e09d05
        - structure-mutator@0.1.0-BETA+358e09d05
        - structure-sponge-loader@1.0.0-BETA+358e09d05
        - structure-terrascript-loader@1.1.0-BETA+358e09d05
        - terra@1.0.0
        - terrascript-function-sampler@1.0.0-BETA+358e09d05
05:00:15 [WARN ] The biome-provider-pipeline addon is deprecated and scheduled for removal in Terra 7.0. It is recommended to use the biome-provider-pipeline-v2 addon for future pack development instead.
05:00:15 [WARN ] The biome-provider-image addon is deprecated and scheduled for removal in Terra 7.0. It is recommended to use the biome-provider-image-v2 addon for future pack development instead.
05:00:15 [INFO ] Terra addons successfully loaded.
05:00:15 [INFO ] Finished initialization.
05:00:17 [ERROR] Catching
java.lang.ExceptionInInitializerError: null
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?]
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:540) ~[?:?]
        at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567) ~[?:?]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:670) ~[?:?]
        at java.util.stream.Nodes.collect(Nodes.java:328) ~[?:?]
        at java.util.stream.ReferencePipeline.evaluateToNode(ReferencePipeline.java:111) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:570) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
        at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
        at com.dfsek.terra.addons.terrascript.TerraScriptAddon.lambda$initialize$1(TerraScriptAddon.java:57) ~[?:?]
        at com.dfsek.terra.config.fileloaders.LoaderImpl.thenEntries(LoaderImpl.java:49) ~[Terra-Binary-6.3.0-BETA-CONFIG-1.3.3.jar:?]
        at com.dfsek.terra.addons.terrascript.TerraScriptAddon.lambda$initialize$2(TerraScriptAddon.java:40) ~[?:?]
        at com.dfsek.terra.event.EventContextImpl.lambda$handle$0(EventContextImpl.java:50) ~[Terra-Binary-6.3.0-BETA-CONFIG-1.3.3.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.dfsek.terra.event.EventContextImpl.handle(EventContextImpl.java:50) ~[Terra-Binary-6.3.0-BETA-CONFIG-1.3.3.jar:?]
        at com.dfsek.terra.event.FunctionalEventHandlerImpl.lambda$handle$0(FunctionalEventHandlerImpl.java:52) ~[Terra-Binary-6.3.0-BETA-CONFIG-1.3.3.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.dfsek.terra.event.FunctionalEventHandlerImpl.handle(FunctionalEventHandlerImpl.java:48) ~[Terra-Binary-6.3.0-BETA-CONFIG-1.3.3.jar:?]
        at com.dfsek.terra.event.EventManagerImpl.lambda$callEvent$0(EventManagerImpl.java:38) ~[Terra-Binary-6.3.0-BETA-CONFIG-1.3.3.jar:?]
        at java.util.HashMap$Values.forEach(HashMap.java:1073) ~[?:?]
        at com.dfsek.terra.event.EventManagerImpl.callEvent(EventManagerImpl.java:38) ~[Terra-Binary-6.3.0-BETA-CONFIG-1.3.3.jar:?]
        at com.dfsek.terra.config.pack.ConfigPackImpl.<init>(ConfigPackImpl.java:174) ~[Terra-Binary-6.3.0-BETA-CONFIG-1.3.3.jar:?]
        at com.dfsek.terra.config.pack.ConfigPackImpl.<init>(ConfigPackImpl.java:135) ~[Terra-Binary-6.3.0-BETA-CONFIG-1.3.3.jar:?]
        at cn.nukkit.level.terra.PNXPlatform.getInstance(PNXPlatform.java:77) ~[PowerNukkitX-1.20.50-r1.jar:?]
        at cn.nukkit.Server.<init>(Server.java:879) ~[PowerNukkitX-1.20.50-r1.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:160) [PowerNukkitX-1.20.50-r1.jar:?]
Caused by: java.lang.ExceptionInInitializerError
        at cn.nukkit.level.terra.handles.PNXWorldHandle.createBlockState(PNXWorldHandle.java:89) ~[PowerNukkitX-1.20.50-r1.jar:?]
        at com.dfsek.terra.addons.terrascript.script.functions.BlockFunction$Constant.<init>(BlockFunction.java:97) ~[?:?]
        at com.dfsek.terra.addons.terrascript.script.builders.BlockFunctionBuilder.build(BlockFunctionBuilder.java:37) ~[?:?]
        at com.dfsek.terra.addons.terrascript.script.builders.BlockFunctionBuilder.build(BlockFunctionBuilder.java:22) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.Parser.parseFunction(Parser.java:453) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.Parser.parseItem(Parser.java:385) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.Parser.parseBlock(Parser.java:362) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.Parser.parse(Parser.java:96) ~[?:?]
        at com.dfsek.terra.addons.terrascript.script.StructureScript.<init>(StructureScript.java:127) ~[?:?]
        at com.dfsek.terra.addons.terrascript.TerraScriptAddon.lambda$initialize$0(TerraScriptAddon.java:52) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1858) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2183) ~[?:?]
        at java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2149) ~[?:?]
        at java.util.stream.AbstractTask.compute(AbstractTask.java:327) ~[?:?]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "<local7>" is null
        at cn.nukkit.jemapping.JeMapping.computeBedrockBlockStateHash(JeMapping.java:105) ~[PowerNukkitX-1.20.50-r1.jar:?]
        at cn.nukkit.jemapping.JeMapping.lambda$init$0(JeMapping.java:69) ~[PowerNukkitX-1.20.50-r1.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:729) ~[?:?]
        at cn.nukkit.jemapping.JeMapping.init(JeMapping.java:67) ~[PowerNukkitX-1.20.50-r1.jar:?]
        at cn.nukkit.jemapping.JeMapping.<clinit>(JeMapping.java:36) ~[PowerNukkitX-1.20.50-r1.jar:?]
        at cn.nukkit.level.terra.handles.PNXWorldHandle.createBlockState(PNXWorldHandle.java:89) ~[PowerNukkitX-1.20.50-r1.jar:?]
        at com.dfsek.terra.addons.terrascript.script.functions.BlockFunction$Constant.<init>(BlockFunction.java:97) ~[?:?]
        at com.dfsek.terra.addons.terrascript.script.builders.BlockFunctionBuilder.build(BlockFunctionBuilder.java:37) ~[?:?]
        at com.dfsek.terra.addons.terrascript.script.builders.BlockFunctionBuilder.build(BlockFunctionBuilder.java:22) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.Parser.parseFunction(Parser.java:453) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.Parser.parseItem(Parser.java:385) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.Parser.parseBlock(Parser.java:362) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.Parser.parse(Parser.java:96) ~[?:?]
        at com.dfsek.terra.addons.terrascript.script.StructureScript.<init>(StructureScript.java:127) ~[?:?]
        at com.dfsek.terra.addons.terrascript.TerraScriptAddon.lambda$initialize$0(TerraScriptAddon.java:52) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1858) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2183) ~[?:?]
        at java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2149) ~[?:?]
        at java.util.stream.AbstractTask.compute(AbstractTask.java:327) ~[?:?]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
05:00:17 [INFO ] Stopping other threads
```

**Comment by MisledWater79** [comment]
This happens to me as well, it occurs when terra is turned on. Seems like it might be trying to get a outdated version.

**Comment by KoshakMineDEV** [comment]
Because PNX legacy 1.20.50-r1 doesn't have mappings updated for terra. Legacy is no more actively supported and all issues about it shouls be in PNX legacy repo.

**Comment by eat-sleep-code** [comment]
Ok, I must have missed something about PNX being updated?

**Comment by KoshakMineDEV** [comment]
Currently there is big WIP refactoring update - 2.0. Versions like 1.20.50-r1 and older - legacy.

**Comment by eat-sleep-code** [comment]
So, sounds like 2.0.0 is not ready for use yet?   And 1.20.50 doesn't work correctly (and older doesn't work with current clients)?

That is disappointing.

**Comment by KoshakMineDEV** [comment]
U are right. 2.0 is not ready for production. Legacy versions of PNX are now mostly community driven, PNX maintainers won't support it, but if you want - you can fix something(for example terra mappings) and make PR with it

**Comment by eat-sleep-code** [comment]
I don't need yet another dev project at the moment, so guess I will revisit later to see if someone else in the community fixes it. 😆

**Comment by CoolLoong** [comment]
the old pnx, please refer to https://github.com/PowerNukkitX/PowerNukkitX-Legacy
