### ISSUE TITLE
Player Login Failure Due to PluginI18n Error

### ISSUE THREAD

**Issue by Mcayear** [PowerNukkitX/PowerNukkitX#1500]
### Issue Description
Players are unable to log in to the server due to a recurring error within the PluginI18n component. The error arises from a NullPointerException, halting the login process and preventing players from accessing the server.

### Error Details
```
10:07:00 [main] [INFO ] Mcayear[/127.0.0.1:55502] 登入游戏，实体 ID 为 1，坐标位于 (world Dim0, 128.2938, 5.0, 132.9991)
10:07:04 [main] [ERROR] A RuntimeException happened while ticking the server
java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because "map" is null
        at cn.nukkit.lang.PluginI18n.get(PluginI18n.java:115) ~[PowerNukkitX.jar:?]
        at cn.nukkit.lang.PluginI18n.parseLanguageText(PluginI18n.java:145) ~[PowerNukkitX.jar:?]
        at cn.nukkit.lang.PluginI18n.tr(PluginI18n.java:60) ~[PowerNukkitX.jar:?]
        at cn.nukkit.lang.PluginI18n.tr(PluginI18n.java:46) ~[PowerNukkitX.jar:?]
        at cn.nukkit.command.Command.generateCustomCommandData(Command.java:136) ~[PowerNukkitX.jar:?]
        at cn.nukkit.Player.sendCommandData(Player.java:2003) ~[PowerNukkitX.jar:?]
        at cn.nukkit.Player.setEnableClientCommand(Player.java:1988) ~[PowerNukkitX.jar:?]
        at cn.nukkit.Player.doFirstSpawn(Player.java:637) ~[PowerNukkitX.jar:?]
        at cn.nukkit.Player.checkNetwork(Player.java:3035) ~[PowerNukkitX.jar:?]
        at cn.nukkit.Server.tick(Server.java:1183) ~[PowerNukkitX.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:1048) [PowerNukkitX.jar:?]
        at cn.nukkit.Server.start(Server.java:1029) [PowerNukkitX.jar:?]
        at cn.nukkit.Server.<init>(Server.java:868) [PowerNukkitX.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:154) [PowerNukkitX.jar:?]
10:08:57 [main] [INFO ] Mcayear[/127.0.0.1:55502] 登出游戏，原因：disconnect.closed
```
- Error Message: `java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because "map" is null`
- Error Source: `cn.nukkit.lang.PluginI18n.get(PluginI18n.java:115)`
- Server Version: PowerNukkitX 2.0.0-SNAPSHOT (git-2b6747d)
- Minecraft: BE Version: 1.20.60 (Protocol Version: 649)

### Steps to Reproduce
1. Attempt to log in to the server.
2. Observe the server log for error messages.

### Expected Behavior
Players should be able to successfully log in to the server without encountering any errors.

### Actual Behavior
The PluginI18n error disrupts the login process, causing players to be unable to access the server.

### Impact
This issue significantly impacts the server's functionality as it prevents players from joining the game. It requires immediate attention to restore normal server operation.

### Proposed Solution
Investigate and resolve the underlying cause of the NullPointerException within the PluginI18n component to restore player login functionality.

### Additional Information
- The error seems to stem from a null map reference, indicating a potential initialization or configuration issue within the PluginI18n module.
- Addressing this issue promptly is crucial to maintaining a seamless gameplay experience for all players on the server.

**Comment by CoolLoong** [comment]
please change the format from `.lang` to `.json`
