### ISSUE TITLE
Terra

### ISSUE THREAD

**Issue by n15421** [PowerNukkitX/PowerNukkitX#1501]
13:17:23 [ERROR] Catching
java.lang.ExceptionInInitializerError: null
        at cn.nukkit.level.terra.handles.PNXWorldHandle.createBlockState(PNXWorldHandle.java:89) ~[PowerNukkitX-1.20.50-r1.jar:?]
        at com.dfsek.terra.addons.terrascript.script.functions.BlockFunction$Constant.<init>(BlockFunction.java:97) ~[?:?]
        at com.dfsek.terra.addons.terrascript.script.builders.BlockFunctionBuilder.build(BlockFunctionBuilder.java:37) ~[?:?]
        at com.dfsek.terra.addons.terrascript.script.builders.BlockFunctionBuilder.build(BlockFunctionBuilder.java:22) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.Parser.parseFunction(Parser.java:453) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.Parser.parseItem(Parser.java:385) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.Parser.parseBlock(Parser.java:362) ~[?:?]
        at com.dfsek.terra.addons.terrascript.parser.Parser.parse(Parser.java:96) ~[?:?]
        at com.dfsek.terra.addons.terrascript.script.StructureScript.<init>(StructureScript.java:127) ~[?:?]
        at com.dfsek.terra.addons.terrascript.TerraScriptAddon.lambda$initialize$0(TerraScriptAddon.java:52) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2183) ~[?:?]
        at java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2149) ~[?:?]
        at java.util.stream.AbstractTask.compute(AbstractTask.java:327) ~[?:?]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686) ~[?:?]
        at java.util.stream.Nodes.collect(Nodes.java:328) ~[?:?]
        at java.util.stream.ReferencePipeline.evaluateToNode(ReferencePipeline.java:111) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:570) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
        at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
        at com.dfsek.terra.addons.terrascript.TerraScriptAddon.lambda$initialize$1(TerraScriptAddon.java:57) ~[?:?]
        at com.dfsek.terra.config.fileloaders.LoaderImpl.thenEntries(LoaderImpl.java:49) ~[Terra-Binary-6.3.0-BETA-CONFIG-1.3.3.jar:?]
        at com.dfsek.terra.addons.terrascript.TerraScriptAddon.lambda$initialize$2(TerraScriptAddon.java:40) ~[?:?]
        at com.dfsek.terra.event.EventContextImpl.lambda$handle$0(EventContextImpl.java:50) ~[Terra-Binary-6.3.0-BETA-CONFIG-1.3.3.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.dfsek.terra.event.EventContextImpl.handle(EventContextImpl.java:50) ~[Terra-Binary-6.3.0-BETA-CONFIG-1.3.3.jar:?]
        at com.dfsek.terra.event.FunctionalEventHandlerImpl.lambda$handle$0(FunctionalEventHandlerImpl.java:52) ~[Terra-Binary-6.3.0-BETA-CONFIG-1.3.3.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.dfsek.terra.event.FunctionalEventHandlerImpl.handle(FunctionalEventHandlerImpl.java:48) ~[Terra-Binary-6.3.0-BETA-CONFIG-1.3.3.jar:?]
        at com.dfsek.terra.event.EventManagerImpl.lambda$callEvent$0(EventManagerImpl.java:38) ~[Terra-Binary-6.3.0-BETA-CONFIG-1.3.3.jar:?]
        at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
(full error log https://paste.ubuntu.com/p/v9gXRThqfr/)
nukkit.yml:
[pnx.zip](https://github.com/PowerNukkitX/PowerNukkitX/files/14231373/pnx.zip)

**Comment by CoolLoong** [comment]
it hasn't been updated yet
