### ISSUE TITLE
[BUG] /relaod also reloads custom items

### ISSUE THREAD

**Issue by AzaleeX** [PowerNukkitX/PowerNukkitX#1525]
### /reload

`reload custom items` the problem is that the server doesn't like the item to be reloaded twice, which **_crashes the server_**

```sh
java.lang.RuntimeException: cn.nukkit.registry.RegisterException: This item has already been registered with the identifier: arkazia:settings
	at cn.nukkit.registry.ItemRegistry.registerCustomItem(ItemRegistry.java:638) ~[powernukkitx.jar:?]
	at cn.nukkit.registry.ItemRegistry.registerCustomItem(ItemRegistry.java:611) ~[powernukkitx.jar:?]
	at fr.arkazia.libs.ArkaziaLib.onLoad(ArkaziaLib.java:42) ~[?:?]
	at cn.nukkit.plugin.JavaPluginLoader.initPlugin(JavaPluginLoader.java:115) ~[powernukkitx.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:63) ~[powernukkitx.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:119) ~[powernukkitx.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:295) ~[powernukkitx.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:156) ~[powernukkitx.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:148) ~[powernukkitx.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:144) ~[powernukkitx.jar:?]
	at cn.nukkit.Server.reload(Server.java:922) ~[powernukkitx.jar:?]
	at cn.nukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:38) ~[powernukkitx.jar:?]
	at cn.nukkit.command.SimpleCommandMap.executeCommand(SimpleCommandMap.java:310) ~[powernukkitx.jar:?]
	at cn.nukkit.Server.executeCommand(Server.java:1493) ~[powernukkitx.jar:?]
	at cn.nukkit.console.NukkitConsole.lambda$runCommand$0(NukkitConsole.java:34) ~[powernukkitx.jar:?]
	at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:95) [powernukkitx.jar:?]
	at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:368) [powernukkitx.jar:?]
	at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:350) [powernukkitx.jar:?]
	at cn.nukkit.Server.tick(Server.java:1180) [powernukkitx.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1050) [powernukkitx.jar:?]
	at cn.nukkit.Server.start(Server.java:1031) [powernukkitx.jar:?]
	at cn.nukkit.Server.<init>(Server.java:831) [powernukkitx.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:154) [powernukkitx.jar:?]
Caused by: cn.nukkit.registry.RegisterException: This item has already been registered with the identifier: arkazia:settings
	at cn.nukkit.registry.ItemRegistry.registerCustomItem(ItemRegistry.java:630) ~[powernukkitx.jar:?]
	... 22 more
2024-03-01 17:19:31 [main] ERROR - Could not load plugin "ArkaziaLibs
2024-03-01 17:19:31 [main] ERROR - Could not load plugin "ArkaziaLobby": Missing dependent plugin named "ArkaziaLibs
2024-03-01 17:19:31 [main] INFO  - Loading spark v1.10.60
2024-03-01 17:19:31 [main] ERROR - Could not load plugin "ArkaziaLobby": Missing dependent plugin named "ArkaziaLibs
2024-03-01 17:19:31 [main] ERROR - Could not load plugin "ArkaziaLobby": Circular dependency detected
```

**Comment by CoolLoong** [comment]
You just need to catch and ignore this exception

**Comment by AzaleeX** [comment]
```java
try {
            Registries.ITEM.registerCustomItem(this, SettingsItem.class, ProfileItem.class, LeaveItem.class);
        } catch (RegisterException e) {
            throw new RuntimeException(e);
        }
```

**Comment by MEFRREEX** [comment]
> ```java
> try {
>             Registries.ITEM.registerCustomItem(this, SettingsItem.class, ProfileItem.class, LeaveItem.class);
>         } catch (RegisterException e) {
>             throw new RuntimeException(e);
>         }
> ```
I think Cool_Loong means you should just ignore the exception
(Remove throw new RuntimeException(e);)

**Comment by AzaleeX** [comment]
> > ```java
> > try {
> >             Registries.ITEM.registerCustomItem(this, SettingsItem.class, ProfileItem.class, LeaveItem.class);
> >         } catch (RegisterException e) {
> >             throw new RuntimeException(e);
> >         }
> > ```
> 
> I think Cool_Loong means you should just ignore the exception (Remove throw new RuntimeException(e);)

so remove the try catch

**Comment by AzaleeX** [comment]
since you closed this issue the problem persists
