### ISSUE TITLE
Could not load level "world": Unknown provider

### ISSUE THREAD

**Issue by MrHoller** [PowerNukkitX/PowerNukkitX#1536]
At the first start of the core, gives an error:
```
18:00:42 [main] [ERROR] Could not load level "world": Unknown provider
18:00:42 [main] [ERROR] Could not generate level "world": cn.nukkit.utils.LevelException: Constructor of class cn.nukkit.level.format.leveldb.LevelDBProvider failed
        at cn.nukkit.level.Level.<init>(Level.java:324)
        at cn.nukkit.Server.generateLevel(Server.java:2548)
        at cn.nukkit.Server.loadLevels(Server.java:841)
        at cn.nukkit.Server.<init>(Server.java:801)
        at cn.nukkit.Nukkit.main(Nukkit.java:152)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at cn.nukkit.level.Level.<init>(Level.java:322)
        ... 4 more
Caused by: net.daporkchop.ldbjni.exception.DBNotFoundException: NotFound: C:\Users\mrhol\OneDrive\Рабочий стол\pnx\worlds\world\db/LOCK: Ñèñòåìå íå óäàåòñÿ íàéòè óêàçàííûé ïóòü.

        at net.daporkchop.ldbjni.natives.NativeDB.openDb(Native Method)
        at net.daporkchop.ldbjni.natives.NativeDB.<init>(NativeDB.java:94)
        at net.daporkchop.ldbjni.natives.NativeDBProvider.open(NativeDBProvider.java:66)
        at cn.nukkit.level.format.leveldb.LevelDBStorage.<init>(LevelDBStorage.java:39)
        at cn.nukkit.level.format.leveldb.LevelDBProvider.lambda$new$0(LevelDBProvider.java:75)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at cn.nukkit.level.format.leveldb.LevelDBProvider.<init>(LevelDBProvider.java:70)
        ... 10 more

cn.nukkit.utils.LevelException: Constructor of class cn.nukkit.level.format.leveldb.LevelDBProvider failed
        at cn.nukkit.level.Level.<init>(Level.java:324) ~[powernukkitx.jar:?]
        at cn.nukkit.Server.generateLevel(Server.java:2548) [powernukkitx.jar:?]
        at cn.nukkit.Server.loadLevels(Server.java:841) [powernukkitx.jar:?]
        at cn.nukkit.Server.<init>(Server.java:801) [powernukkitx.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:152) [powernukkitx.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at cn.nukkit.level.Level.<init>(Level.java:322) ~[powernukkitx.jar:?]
        ... 4 more
Caused by: net.daporkchop.ldbjni.exception.DBNotFoundException: NotFound: C:\Users\mrhol\OneDrive\Рабочий стол\pnx\worlds\world\db/LOCK: Ñèñòåìå íå óäàåòñÿ íàéòè óêàçàííûé ïóòü.

        at net.daporkchop.ldbjni.natives.NativeDB.openDb(Native Method) ~[leveldb-mcpe-jni-0.0.10-SNAPSHOT.jar:?]
        at net.daporkchop.ldbjni.natives.NativeDB.<init>(NativeDB.java:94) ~[leveldb-mcpe-jni-0.0.10-SNAPSHOT.jar:?]
        at net.daporkchop.ldbjni.natives.NativeDBProvider.open(NativeDBProvider.java:66) ~[leveldb-mcpe-jni-0.0.10-SNAPSHOT.jar:?]
        at cn.nukkit.level.format.leveldb.LevelDBStorage.<init>(LevelDBStorage.java:39) ~[powernukkitx.jar:?]
        at cn.nukkit.level.format.leveldb.LevelDBProvider.lambda$new$0(LevelDBProvider.java:75) ~[powernukkitx.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
        at cn.nukkit.level.format.leveldb.LevelDBProvider.<init>(LevelDBProvider.java:70) ~[powernukkitx.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at cn.nukkit.level.Level.<init>(Level.java:322) ~[powernukkitx.jar:?]
        ... 4 more
18:00:42 [main] [ERROR] Could not load level "world": Unknown provider
18:00:42 [main] [ERROR] Could not generate level "world": cn.nukkit.utils.LevelException: Constructor of class cn.nukkit.level.format.leveldb.LevelDBProvider failed
        at cn.nukkit.level.Level.<init>(Level.java:324)
        at cn.nukkit.Server.generateLevel(Server.java:2548)
        at cn.nukkit.Server.loadLevels(Server.java:868)
        at cn.nukkit.Server.<init>(Server.java:801)
        at cn.nukkit.Nukkit.main(Nukkit.java:152)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at cn.nukkit.level.Level.<init>(Level.java:322)
        ... 4 more
Caused by: net.daporkchop.ldbjni.exception.DBNotFoundException: NotFound: C:\Users\mrhol\OneDrive\Рабочий стол\pnx\worlds\world\db/LOCK: Ñèñòåìå íå óäàåòñÿ íàéòè óêàçàííûé ïóòü.

        at net.daporkchop.ldbjni.natives.NativeDB.openDb(Native Method)
        at net.daporkchop.ldbjni.natives.NativeDB.<init>(NativeDB.java:94)
        at net.daporkchop.ldbjni.natives.NativeDBProvider.open(NativeDBProvider.java:66)
        at cn.nukkit.level.format.leveldb.LevelDBStorage.<init>(LevelDBStorage.java:39)
        at cn.nukkit.level.format.leveldb.LevelDBProvider.lambda$new$0(LevelDBProvider.java:75)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at cn.nukkit.level.format.leveldb.LevelDBProvider.<init>(LevelDBProvider.java:70)
        ... 10 more

cn.nukkit.utils.LevelException: Constructor of class cn.nukkit.level.format.leveldb.LevelDBProvider failed
        at cn.nukkit.level.Level.<init>(Level.java:324) ~[powernukkitx.jar:?]
        at cn.nukkit.Server.generateLevel(Server.java:2548) [powernukkitx.jar:?]
        at cn.nukkit.Server.loadLevels(Server.java:868) [powernukkitx.jar:?]
        at cn.nukkit.Server.<init>(Server.java:801) [powernukkitx.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:152) [powernukkitx.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at cn.nukkit.level.Level.<init>(Level.java:322) ~[powernukkitx.jar:?]
        ... 4 more
Caused by: net.daporkchop.ldbjni.exception.DBNotFoundException: NotFound: C:\Users\mrhol\OneDrive\Рабочий стол\pnx\worlds\world\db/LOCK: Ñèñòåìå íå óäàåòñÿ íàéòè óêàçàííûé ïóòü.

        at net.daporkchop.ldbjni.natives.NativeDB.openDb(Native Method) ~[leveldb-mcpe-jni-0.0.10-SNAPSHOT.jar:?]
        at net.daporkchop.ldbjni.natives.NativeDB.<init>(NativeDB.java:94) ~[leveldb-mcpe-jni-0.0.10-SNAPSHOT.jar:?]
        at net.daporkchop.ldbjni.natives.NativeDBProvider.open(NativeDBProvider.java:66) ~[leveldb-mcpe-jni-0.0.10-SNAPSHOT.jar:?]
        at cn.nukkit.level.format.leveldb.LevelDBStorage.<init>(LevelDBStorage.java:39) ~[powernukkitx.jar:?]
        at cn.nukkit.level.format.leveldb.LevelDBProvider.lambda$new$0(LevelDBProvider.java:75) ~[powernukkitx.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
        at cn.nukkit.level.format.leveldb.LevelDBProvider.<init>(LevelDBProvider.java:70) ~[powernukkitx.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at cn.nukkit.level.Level.<init>(Level.java:322) ~[powernukkitx.jar:?]
        ... 4 more
18:00:42 [main] [ERROR] No default level has been loaded
>
18:00:42 [main] [INFO ] Stopping other threads
```

**Comment by CoolLoong** [comment]
You can't have non-ascii characters in your level path, you must use English for all of them.
