### ISSUE TITLE
[Bug]: New Issue

### ISSUE THREAD

**Issue by RomaGly55Creations** [PowerNukkitX/PowerNukkitX#1588]
### Describe the bug

21:07:26 [INFO ] Using JVM: Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.3+7.11
21:07:26 [INFO ] Using PNX core: 2.0.0-SNAPSHOT - 509b56a1
java.net.BindException: Cannot assign requested address: bind
        at java.base/sun.nio.ch.Net.bind0(Native Method) ~[?:?]
        at java.base/sun.nio.ch.Net.bind(Net.java:565) ~[?:?]
        at java.base/sun.nio.ch.DatagramChannelImpl.bindInternal(DatagramChannelImpl.java:1329) ~[?:?]
        at java.base/sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:1299) ~[?:?]
        at io.netty.util.internal.SocketUtils$6.run(SocketUtils.java:133) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
        at io.netty.util.internal.SocketUtils$6.run(SocketUtils.java:130) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:571) ~[?:?]
        at io.netty.util.internal.SocketUtils.bind(SocketUtils.java:130) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
        at io.netty.channel.socket.nio.NioDatagramChannel.doBind0(NioDatagramChannel.java:202) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
        at io.netty.channel.socket.nio.NioDatagramChannel.doBind(NioDatagramChannel.java:197) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:600) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:579) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
        at org.cloudburstmc.netty.handler.codec.raknet.ProxyOutboundRouter.bind(ProxyOutboundRouter.java:48) ~[netty-transport-raknet-1.0.0.CR3-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:604) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:579) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
        at org.cloudburstmc.netty.channel.proxy.ProxyChannel.bind(ProxyChannel.java:188) ~[netty-transport-raknet-1.0.0.CR3-SNAPSHOT.jar:?]
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:380) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
21:07:34 [main] [INFO ] Stopping other threads

### To Reproduce

Second test with literally my ip

### Expected behavior

The server should stand open
Anyone will asking to play.

### Version

509b56a1

**Comment by CoolLoong** [comment]
you have started a server on port 19132, check yourself

**Comment by RomaGly55Creations** [comment]
Help plz
https://pastebin.com/yAAKtdsG - here is new issue without bind network, a something worse
