### ISSUE TITLE
[CRASH]Runtime crash in version 0.1.6 on Windows 10

### ISSUE THREAD

**Issue by zhu18qwsr** [PowerNukkitX/PowerNukkitX#1597]
**Java Version Information:**
java version "17.0.11" 2024-04-16 LTS
Java(TM) SE Runtime Environment (build 17.0.11+7-LTS-207)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.11+7-LTS-207, mixed mode, sharing)
**Runtime Log:**
17:26:23 [INFO ] 使用的JVM：Java HotSpot(TM) 64-Bit Server VM
17:26:23 [WARN ] 未发现PNX核心，将要自动安装
17:26:23 [INFO ] 正在使用 nullatom 端点。
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
        at com.google.gson.JsonParser.parseReader(JsonParser.java:66)
        at com.google.gson.JsonParser.parseString(JsonParser.java:47)
        at cn.powernukkitx.cli.data.remote.VersionListHelperV2.getLatestRelease(VersionListHelperV2.java:30)
        at cn.powernukkitx.cli.cmd.ServerCommand.updateLatest(ServerCommand.java:62)
        at cn.powernukkitx.cli.cmd.ServerCommand.call(ServerCommand.java:48)
        at cn.powernukkitx.cli.cmd.StartCommand.call(StartCommand.java:67)
        at cn.powernukkitx.cli.App.call(App.java:68)
        at cn.powernukkitx.cli.App.call(App.java:18)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at cn.powernukkitx.cli.Main.main(Main.java:41)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1597)
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1404)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
        at com.google.gson.JsonParser.parseReader(JsonParser.java:61)
        ... 16 more

**Comment by CoolLoong** [comment]
使用jdk21，并且阅读安装教程https://docs.powernukkitx.com/zh-CN/docs/#%E5%AE%89%E8%A3%85
