### ISSUE TITLE
Error Bootstrap

### ISSUE THREAD

**Issue by PocketMiner92** [PowerNukkitX/PowerNukkitX#226]
# 🐞 错误汇报
 Exception in thread "main" java.lang.UnsatisfiedLinkError: /usr/local/openjdk-17/lib/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory

at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)

at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)

at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)

at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)

at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)

at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)

at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)

at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)

at java.base/java.lang.System.loadLibrary(System.java:1989)

at java.desktop/sun.font.FontManagerNativeLibrary$1.run(FontManagerNativeLibrary.java:58)

at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)

at java.desktop/sun.font.FontManagerNativeLibrary.<clinit>(FontManagerNativeLibrary.java:33)

at java.desktop/sun.font.SunFontManager$1.run(SunFontManager.java:275)

at java.desktop/sun.font.SunFontManager$1.run(SunFontManager.java:273)

at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)

at java.desktop/sun.font.SunFontManager.initStatic(SunFontManager.java:273)

at java.desktop/sun.font.SunFontManager.<clinit>(SunFontManager.java:268)

at java.base/java.lang.Class.forName0(Native Method)

at java.base/java.lang.Class.forName(Class.java:467)

at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)

at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)

at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:75)

at java.desktop/java.awt.Font.getFont2D(Font.java:526)

at java.desktop/java.awt.Font$FontAccessImpl.getFont2D(Font.java:265)

at java.desktop/sun.font.FontUtilities.getFont2D(FontUtilities.java:148)

at java.desktop/sun.font.FontUtilities.fontSupportsDefaultEncoding(FontUtilities.java:339)

at java.desktop/javax.swing.text.StyleContext.getFont(StyleContext.java:284)

at com.formdev.flatlaf.FlatLaf.createCompositeFont(FlatLaf.java:621)

at com.formdev.flatlaf.LinuxFontPolicy.createFont(LinuxFontPolicy.java:156)

at com.formdev.flatlaf.LinuxFontPolicy.createFontEx(LinuxFontPolicy.java:123)

at com.formdev.flatlaf.LinuxFontPolicy.getGnomeFont(LinuxFontPolicy.java:111)

at com.formdev.flatlaf.LinuxFontPolicy.getFont(LinuxFontPolicy.java:44)

at com.formdev.flatlaf.FlatLaf.initDefaultFont(FlatLaf.java:590)

at com.formdev.flatlaf.FlatLaf.getDefaults(FlatLaf.java:445)

at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:593)

at com.formdev.flatlaf.FlatLaf.setup(FlatLaf.java:116)

at com.formdev.flatlaf.FlatDarculaLaf.setup(FlatDarculaLaf.java:39)

at cn.powernukkitx.bootstrap.GUI.exec(GUI.java:10)

at cn.powernukkitx.bootstrap.Bootstrap.main(Bootstrap.java:42)

---------------------------------------

Minecraft Server wird gestartet...

Gestartet am: 16.04.2022 um 10:39:01 Uhr

Server-Software: NUKKIT

Server-Version: stable

JAVA: OPENJDK-17

RAM: 4096 MB

---------------------------------------

Exception in thread "main" java.lang.UnsatisfiedLinkError: /usr/local/openjdk-17/lib/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory

at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)

at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)

at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)

at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)

at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)

at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)

at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)

at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)

at java.base/java.lang.System.loadLibrary(System.java:1989)

at java.desktop/sun.font.FontManagerNativeLibrary$1.run(FontManagerNativeLibrary.java:58)

at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)

at java.desktop/sun.font.FontManagerNativeLibrary.<clinit>(FontManagerNativeLibrary.java:33)

at java.desktop/sun.font.SunFontManager$1.run(SunFontManager.java:275)

at java.desktop/sun.font.SunFontManager$1.run(SunFontManager.java:273)

at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)

at java.desktop/sun.font.SunFontManager.initStatic(SunFontManager.java:273)

at java.desktop/sun.font.SunFontManager.<clinit>(SunFontManager.java:268)

at java.base/java.lang.Class.forName0(Native Method)

at java.base/java.lang.Class.forName(Class.java:467)

at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)

at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)

at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:75)

at java.desktop/java.awt.Font.getFont2D(Font.java:526)

at java.desktop/java.awt.Font$FontAccessImpl.getFont2D(Font.java:265)

at java.desktop/sun.font.FontUtilities.getFont2D(FontUtilities.java:148)

at java.desktop/sun.font.FontUtilities.fontSupportsDefaultEncoding(FontUtilities.java:339)

at java.desktop/javax.swing.text.StyleContext.getFont(StyleContext.java:284)

at com.formdev.flatlaf.FlatLaf.createCompositeFont(FlatLaf.java:621)

at com.formdev.flatlaf.LinuxFontPolicy.createFont(LinuxFontPolicy.java:156)

at com.formdev.flatlaf.LinuxFontPolicy.createFontEx(LinuxFontPolicy.java:123)

at com.formdev.flatlaf.LinuxFontPolicy.getGnomeFont(LinuxFontPolicy.java:111)

at com.formdev.flatlaf.LinuxFontPolicy.getFont(LinuxFontPolicy.java:44)

at com.formdev.flatlaf.FlatLaf.initDefaultFont(FlatLaf.java:590)

at com.formdev.flatlaf.FlatLaf.getDefaults(FlatLaf.java:445)

at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:593)

at com.formdev.flatlaf.FlatLaf.setup(FlatLaf.java:116)

at com.formdev.flatlaf.FlatDarculaLaf.setup(FlatDarculaLaf.java:39)

at cn.powernukkitx.bootstrap.GUI.exec(GUI.java:10)

at cn.powernukkitx.bootstrap.Bootstrap.main(Bootstrap.java:42)

---------------------------------------

Minecraft Server wird gestartet...

Gestartet am: 16.04.2022 um 10:39:27 Uhr

Server-Software: NUKKIT

Server-Version: stable

JAVA: OPENJDK-17

RAM: 4096 MB

---------------------------------------

Exception in thread "main" java.lang.UnsatisfiedLinkError: /usr/local/openjdk-17/lib/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory

at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)

at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)

at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)

at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)

at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)

at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)

at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)

at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)

at java.base/java.lang.System.loadLibrary(System.java:1989)

at java.desktop/sun.font.FontManagerNativeLibrary$1.run(FontManagerNativeLibrary.java:58)

at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)

at java.desktop/sun.font.FontManagerNativeLibrary.<clinit>(FontManagerNativeLibrary.java:33)

at java.desktop/sun.font.SunFontManager$1.run(SunFontManager.java:275)

at java.desktop/sun.font.SunFontManager$1.run(SunFontManager.java:273)

at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)

at java.desktop/sun.font.SunFontManager.initStatic(SunFontManager.java:273)

at java.desktop/sun.font.SunFontManager.<clinit>(SunFontManager.java:268)

at java.base/java.lang.Class.forName0(Native Method)

at java.base/java.lang.Class.forName(Class.java:467)

at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)

at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)

at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:75)

at java.desktop/java.awt.Font.getFont2D(Font.java:526)

at java.desktop/java.awt.Font$FontAccessImpl.getFont2D(Font.java:265)

at java.desktop/sun.font.FontUtilities.getFont2D(FontUtilities.java:148)

at java.desktop/sun.font.FontUtilities.fontSupportsDefaultEncoding(FontUtilities.java:339)

at java.desktop/javax.swing.text.StyleContext.getFont(StyleContext.java:284)

at com.formdev.flatlaf.FlatLaf.createCompositeFont(FlatLaf.java:621)

at com.formdev.flatlaf.LinuxFontPolicy.createFont(LinuxFontPolicy.java:156)

at com.formdev.flatlaf.LinuxFontPolicy.createFontEx(LinuxFontPolicy.java:123)

at com.formdev.flatlaf.LinuxFontPolicy.getGnomeFont(LinuxFontPolicy.java:111)

at com.formdev.flatlaf.LinuxFontPolicy.getFont(LinuxFontPolicy.java:44)

at com.formdev.flatlaf.FlatLaf.initDefaultFont(FlatLaf.java:590)

at com.formdev.flatlaf.FlatLaf.getDefaults(FlatLaf.java:445)

at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:593)

at com.formdev.flatlaf.FlatLaf.setup(FlatLaf.java:116)

at com.formdev.flatlaf.FlatDarculaLaf.setup(FlatDarculaLaf.java:39)

at cn.powernukkitx.bootstrap.GUI.exec(GUI.java:10)

at cn.powernukkitx.bootstrap.Bootstrap.main(Bootstrap.java:42)

**Comment by zimzaza4** [comment]
umm try use Java 8 to start the bootstrap

**Comment by smartcmd** [comment]
why you use this chinese bauble? PN is better than PNX ^_^

**Comment by PocketMiner92** [comment]
Apr 16, 2022 11:11:55 AM com.formdev.flatlaf.util.LoggingFacadeImpl logSevere

SEVERE: FlatLaf: Failed to setup look and feel 'com.formdev.flatlaf.FlatDarculaLaf'.

java.lang.NullPointerException

at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)

at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)

at sun.awt.FontConfiguration.init(FontConfiguration.java:107)

at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)

at sun.font.SunFontManager$2.run(SunFontManager.java:431)

at java.security.AccessController.doPrivileged(Native Method)

at sun.font.SunFontManager.<init>(SunFontManager.java:376)

at sun.awt.FcFontManager.<init>(FcFontManager.java:35)

at sun.awt.X11FontManager.<init>(X11FontManager.java:57)

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

at java.lang.Class.newInstance(Class.java:442)

at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)

at java.security.AccessController.doPrivileged(Native Method)

at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)

at java.awt.Font.getFont2D(Font.java:491)

at java.awt.Font.access$000(Font.java:224)

at java.awt.Font$FontAccessImpl.getFont2D(Font.java:228)

at sun.font.FontUtilities.getFont2D(FontUtilities.java:180)

at sun.font.FontUtilities.fontSupportsDefaultEncoding(FontUtilities.java:338)

at javax.swing.text.StyleContext.getFont(StyleContext.java:266)

at com.formdev.flatlaf.FlatLaf.createCompositeFont(FlatLaf.java:621)

at com.formdev.flatlaf.LinuxFontPolicy.createFont(LinuxFontPolicy.java:156)

at com.formdev.flatlaf.LinuxFontPolicy.createFontEx(LinuxFontPolicy.java:123)

at com.formdev.flatlaf.LinuxFontPolicy.getGnomeFont(LinuxFontPolicy.java:111)

at com.formdev.flatlaf.LinuxFontPolicy.getFont(LinuxFontPolicy.java:44)

at com.formdev.flatlaf.FlatLaf.initDefaultFont(FlatLaf.java:590)

at com.formdev.flatlaf.FlatLaf.getDefaults(FlatLaf.java:445)

at javax.swing.UIManager.setLookAndFeel(UIManager.java:539)

at com.formdev.flatlaf.FlatLaf.setup(FlatLaf.java:116)

at com.formdev.flatlaf.FlatDarculaLaf.setup(FlatDarculaLaf.java:39)

at cn.powernukkitx.bootstrap.GUI.exec(GUI.java:10)

at cn.powernukkitx.bootstrap.Bootstrap.main(Bootstrap.java:42)


Exception in thread "main" java.awt.HeadlessException:

No X11 DISPLAY variable was set, but this program performed an operation which requires it.

at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)

at java.awt.Window.<init>(Window.java:536)

at java.awt.Frame.<init>(Frame.java:420)

at java.awt.Frame.<init>(Frame.java:385)

at javax.swing.JFrame.<init>(JFrame.java:188)

at cn.powernukkitx.bootstrap.gui.view.impl.main.MainWindowView.<init>(MainWindowView.java:25)

at cn.powernukkitx.bootstrap.gui.controller.MainWindowController.<init>(MainWindowController.java:41)

at cn.powernukkitx.bootstrap.GUI.exec(GUI.java:12)

at cn.powernukkitx.bootstrap.Bootstrap.main(Bootstrap.java:42)


Apr 16, 2022 11:13:25 AM com.formdev.flatlaf.util.LoggingFacadeImpl logSevere

SEVERE: FlatLaf: Failed to setup look and feel 'com.formdev.flatlaf.FlatDarculaLaf'.

java.lang.NullPointerException

at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)

at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)

at sun.awt.FontConfiguration.init(FontConfiguration.java:107)

at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)

at sun.font.SunFontManager$2.run(SunFontManager.java:431)

at java.security.AccessController.doPrivileged(Native Method)

at sun.font.SunFontManager.<init>(SunFontManager.java:376)

at sun.awt.FcFontManager.<init>(FcFontManager.java:35)

at sun.awt.X11FontManager.<init>(X11FontManager.java:57)

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

at java.lang.Class.newInstance(Class.java:442)

at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)

at java.security.AccessController.doPrivileged(Native Method)

at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)

at java.awt.Font.getFont2D(Font.java:491)

at java.awt.Font.access$000(Font.java:224)

at java.awt.Font$FontAccessImpl.getFont2D(Font.java:228)

at sun.font.FontUtilities.getFont2D(FontUtilities.java:180)

at sun.font.FontUtilities.fontSupportsDefaultEncoding(FontUtilities.java:338)

at javax.swing.text.StyleContext.getFont(StyleContext.java:266)

at com.formdev.flatlaf.FlatLaf.createCompositeFont(FlatLaf.java:621)

at com.formdev.flatlaf.LinuxFontPolicy.createFont(LinuxFontPolicy.java:156)

at com.formdev.flatlaf.LinuxFontPolicy.createFontEx(LinuxFontPolicy.java:123)

at com.formdev.flatlaf.LinuxFontPolicy.getGnomeFont(LinuxFontPolicy.java:111)

at com.formdev.flatlaf.LinuxFontPolicy.getFont(LinuxFontPolicy.java:44)

at com.formdev.flatlaf.FlatLaf.initDefaultFont(FlatLaf.java:590)

at com.formdev.flatlaf.FlatLaf.getDefaults(FlatLaf.java:445)

at javax.swing.UIManager.setLookAndFeel(UIManager.java:539)

at com.formdev.flatlaf.FlatLaf.setup(FlatLaf.java:116)

at com.formdev.flatlaf.FlatDarculaLaf.setup(FlatDarculaLaf.java:39)

at cn.powernukkitx.bootstrap.GUI.exec(GUI.java:10)

at cn.powernukkitx.bootstrap.Bootstrap.main(Bootstrap.java:42)


Exception in thread "main" java.awt.HeadlessException:

No X11 DISPLAY variable was set, but this program performed an operation which requires it.

at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)

at java.awt.Window.<init>(Window.java:536)

at java.awt.Frame.<init>(Frame.java:420)

at java.awt.Frame.<init>(Frame.java:385)

at javax.swing.JFrame.<init>(JFrame.java:188)

at cn.powernukkitx.bootstrap.gui.view.impl.main.MainWindowView.<init>(MainWindowView.java:25)

at cn.powernukkitx.bootstrap.gui.controller.MainWindowController.<init>(MainWindowController.java:41)

at cn.powernukkitx.bootstrap.GUI.exec(GUI.java:12)

at cn.powernukkitx.bootstrap.Bootstrap.main(Bootstrap.java:42)

**Comment by smartcmd** [comment]
![image](https://user-images.githubusercontent.com/60499296/163669512-003ac0f0-d660-404e-b2a8-1c5a0fba214f.png)

**Comment by smartcmd** [comment]
use cli mode

**Comment by smartcmd** [comment]
your environment doesn't support GUI

**Comment by PocketMiner92** [comment]
Same error

**Comment by zimzaza4** [comment]
java -jar bootstrap.jar --cli

**Comment by PocketMiner92** [comment]
Closed because noone have a Plan for a fix.
I have reported this Issue at Discord, and now Here and noone have any correct solutions.
Its Not working for Gameservers.

**Comment by zimzaza4** [comment]
> java -jar bootstrap.jar --cli

so it's useless?

**Comment by PocketMiner92** [comment]
Yes because in Gameserver you cant use this.
You should learn More about Gameservers.

**Comment by CoolLoong** [comment]
> Yes because in Gameserver you cant use this. You should learn More about Gameservers.

Another way is to modify the config file
In the current directory of the bootstarp.
modify "#display = cli" to "display = cli" in config.ini

**Comment by PocketMiner92** [comment]
boostrap.ini?

This the Auto generated file

**Comment by CoolLoong** [comment]
> boostrap.ini?
> 
> This the Auto generated file

yes,modify "#display = cli" to "display = cli" in config.ini

**Comment by PocketMiner92** [comment]
Doenst work.
I have tested it with gui and cli and i get the Same Error for gui

**Comment by PocketMiner92** [comment]
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
