### ISSUE TITLE
物品的bug

### ISSUE THREAD

**Issue by TCPL2391** [PowerNukkitX/PowerNukkitX#263]
# 🐞 错误汇报
把木头（所有的）制作成木板时显示只有橡木木板

### ▶ 复现步骤
比如撸树得到丛林木，工作台应该合成丛林木木板，结果只有橡木木板可选

### ✔ 预期行为

对应木头合成对应木板

### ❌ 实际行为
只能合成橡木木板

### 📋 Debug information

> timings paste>
                00:48:50 [INFO ] 准备时序报告中...
>
 00:48:51 [INFO ] 查看时序报告：https://timings.aikar.co/?id=60dafee55d984ca3a4f5f7e8075dd1cb
>
 00:48:51 [INFO ] 时序写入 /home/container/timings/timings-2022-04-28-12-48.txt
> debugpaste upload>
                    00:49:38 [INFO ] The /debugpaste is executing, please wait...
>
 00:49:38 [INFO ] A debug paste was created at debugpastes/debugpaste-2022-04-28T00.49.38.933+0800.zip
>
 00:49:38 [INFO ] Uploading...
>
 00:49:40 [ERROR] Failed to upload the debugpaste /home/container/debugpastes/debugpaste-2022-04-28T00.49.38.933+0800.zip
java.io.IOException: The server responded with code 500, expected 201
        at cn.nukkit.command.defaults.DebugPasteCommand.upload(DebugPasteCommand.java:308) [server.jar:?]
        at cn.nukkit.command.defaults.DebugPasteCommand$1.onRun(DebugPasteCommand.java:201) [server.jar:?]
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:26) [server.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
>
 00:49:40 [INFO ] Failed to upload the debugpaste, the file is still available in your server directory.

### 💬 其他信息

[debugpaste-2022-04-28T00.49.38.933+0800.zip](https://github.com/PowerNukkitX/PowerNukkitX/files/8574694/debugpaste-2022-04-28T00.49.38.933%2B0800.zip)

**Comment by CoolLoong** [comment]
[#80 ](https://github.com/PowerNukkitX/PowerNukkitX/issues/80)
