### ISSUE TITLE
terra跑图出现java.lang.NullPointerException

### ISSUE THREAD

**Issue by CoolLoong** [PowerNukkitX/PowerNukkitX#272]
# 🐞 错误汇报

### ▶ 复现步骤

使用terra生成器快速跑图

### 💢 错误堆栈或崩溃日志

`java.lang.NullPointerException
java.lang.NullPointerException: Cannot invoke "cn.nukkit.level.format.LevelProvider.isOverWorld()" because the return value of "cn.nukkit.level.format.FullChunk.getProvider()" is null
	at cn.nukkit.level.format.FullChunk.isOverWorld(FullChunk.java:282)
	at cn.nukkit.level.generator.SimpleChunkManager.ensureY(SimpleChunkManager.java:166)
	at cn.nukkit.level.generator.SimpleChunkManager.getBlockStateAt(SimpleChunkManager.java:41)
	at cn.nukkit.level.ChunkManager.getBlockStateAt(ChunkManager.java:65)
	at cn.nukkit.level.terra.delegate.PNXProtoWorld.getBlockState(PNXProtoWorld.java:50)
	at com.dfsek.terra.api.world.chunk.generation.util.Column.getBlock(Column.java:40)
	at com.dfsek.terra.addons.feature.locator.patterns.MatchPattern.matches(MatchPattern.java:29)
	at com.dfsek.terra.addons.feature.locator.locators.AdjacentPatternLocator.isValid(AdjacentPatternLocator.java:47)
	at com.dfsek.terra.addons.feature.locator.locators.AdjacentPatternLocator.getSuitableCoordinates(AdjacentPatternLocator.java:33)
	at com.dfsek.terra.api.structure.feature.Locator.lambda$and$0(Locator.java:15)
	at com.dfsek.terra.addons.generation.feature.FeatureGenerationStage.lambda$populate$1(FeatureGenerationStage.java:59)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.dfsek.terra.addons.generation.feature.FeatureGenerationStage.populate(FeatureGenerationStage.java:55)
	at cn.nukkit.level.generator.PNXChunkGeneratorWrapper.populateChunk(PNXChunkGeneratorWrapper.java:185)
	at cn.nukkit.level.generator.task.PopulationTask.generationTask(PopulationTask.java:112)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:48)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.onRun(PopulationTask.java:43)
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:26)`

**Comment by smartcmd** [comment]
我记得这个bug之前修过一遍。。。？

**Comment by CoolLoong** [comment]
> 我记得这个bug之前修过一遍。。。？

这是一个古老的Bug
