### ISSUE TITLE
pnx-js的reload问题

### ISSUE THREAD

**Issue by Mcayear** [PowerNukkitX/PowerNukkitX#300]
# 🐞 错误汇报
```
2022-05-07 10:13:28.295 [main] INFO  - Reloading properties...

2022-05-07 10:13:28.325 [main] INFO  - 读取 LiteLoaderLibs v0.0.1 中
2022-05-07 10:13:28.423 [main] INFO  - 读取 Test v0.0.1 中
2022-05-07 10:13:28.580 [main] FATAL - Could not load plugin
org.graalvm.polyglot.PolyglotException: Timer already cancelled.
	at java.util.Timer.sched(Timer.java:409) ~[?:?]
	at java.util.Timer.schedule(Timer.java:205) ~[?:?]
	at cn.nukkit.plugin.js.JSIInitiator.lambda$initTimer$1(JSIInitiator.java:86) ~[powernukkitx.jar:?]
	at <js>.:module(@Test/main.js:26) ~[?:?]
	at org.graalvm.polyglot.Context.eval(Context.java:399) ~[org.graalvm.sdk:?]
	at cn.nukkit.plugin.CommonJSPlugin.onLoad(CommonJSPlugin.java:94) ~[powernukkitx.jar:?]
	at cn.nukkit.plugin.JSPluginLoader.loadPlugin(JSPluginLoader.java:40) ~[powernukkitx.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:125) ~[powernukkitx.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:296) ~[powernukkitx.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:162) ~[powernukkitx.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:154) ~[powernukkitx.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:150) ~[powernukkitx.jar:?]
	at cn.nukkit.Server.reload(Server.java:1046) ~[powernukkitx.jar:?]
	at cn.nukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[powernukkitx.jar:?]
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:274) ~[powernukkitx.jar:?]
	at cn.nukkit.Server.dispatchCommand(Server.java:998) ~[powernukkitx.jar:?]
	at cn.nukkit.console.NukkitConsole.lambda$runCommand$0(NukkitConsole.java:35) ~[powernukkitx.jar:?]
	at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:100) [powernukkitx.jar:?]
	at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:298) [powernukkitx.jar:?]
	at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:279) [powernukkitx.jar:?]
	at cn.nukkit.Server.tick(Server.java:1404) [powernukkitx.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1179) [powernukkitx.jar:?]
	at cn.nukkit.Server.start(Server.java:1139) [powernukkitx.jar:?]
	at cn.nukkit.Server.<init>(Server.java:808) [powernukkitx.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:209) [powernukkitx.jar:?]
2022-05-07 10:13:28.600 [main] FATAL - 无法读取插件 "Test"
```

### ▶ 复现步骤
如果pnx-js的代码中使用了
setTimeout 或者 setInterval
那么它将不能被正确重载

**Comment by Superice666** [comment]
在 #304 中修复
