### ISSUE TITLE
An error when i stop the server

### ISSUE THREAD

**Issue by AraaCuteUwU** [PowerNukkitX/PowerNukkitX#305]
12:46:58 [INFO ] Unload level "world"
java.lang.reflect.InaccessibleObjectException: Unable to make field java.lang.ThreadLocal$ThreadLocalMap java.lang.Thread.threadLocals accessible: module java.base does not "opens java.lang" to unnamed module @62bd2070
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at cn.nukkit.utils.IterableThreadLocal.clean(IterableThreadLocal.java:55)
        at cn.nukkit.utils.IterableThreadLocal.clean(IterableThreadLocal.java:38)
        at cn.nukkit.level.Level.close(Level.java:568)
        at cn.nukkit.level.Level.unload(Level.java:804)
        at cn.nukkit.Server.unloadLevel(Server.java:2185)
        at cn.nukkit.Server.forceShutdown(Server.java:1113)
        at cn.nukkit.Server.start(Server.java:1164)
        at cn.nukkit.Server.<init>(Server.java:831)
        at cn.nukkit.Nukkit.main(Nukkit.java:209)

**Comment by CoolLoong** [comment]
look here https://doc.powernukkitx.cn/en-us/faq/Server_faq.html
