### ISSUE TITLE
/effect command

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkitX/PowerNukkitX#313]
# 🐞 错误汇报
 
at cn.nukkit.command.CommandParser.parseTargets(CommandParser.java:372)

at cn.nukkit.command.CommandParser.parseTargets(CommandParser.java:360)

at cn.nukkit.command.defaults.EffectCommand.execute(EffectCommand.java:63)

at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:291)

at cn.nukkit.Server.dispatchCommand(Server.java:1021)

at cn.nukkit.Player.handleDataPacket(Player.java:3339)

at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:129)

at cn.nukkit.network.Network.processInterfaces(Network.java:170)

at cn.nukkit.Server.tick(Server.java:1423)

at cn.nukkit.Server.tickProcessor(Server.java:1203)

(git-d512ab7)

**Comment by smartcmd** [comment]
I can't replay this bug

**Comment by smartcmd** [comment]
plz send me your command

**Comment by smartcmd** [comment]
![image](https://user-images.githubusercontent.com/60499296/169538931-b3cbc38f-7915-4a9c-9a66-a187134059e2.png)
![image](https://user-images.githubusercontent.com/60499296/169538926-62f48f3b-abe0-4677-a7cb-c8c187d76d55.png)
I can't recurrent the bug you said:(

**Comment by smartcmd** [comment]
if there are space in username, you should using "" to surround the username

**Comment by MonoAdrian23** [comment]
I have Test it with /effect shortUser night_vision 300

Like /effect pow night_vision 300

**Comment by smartcmd** [comment]
![image](https://user-images.githubusercontent.com/60499296/169540300-e78ed856-4379-4cb4-9c4d-e0e990ba0e60.png)
I meet no problem

**Comment by smartcmd** [comment]
![image](https://user-images.githubusercontent.com/60499296/169540401-0dce9fd1-b0d7-49be-9a5f-58f6763a464d.png)

**Comment by MonoAdrian23** [comment]
OK i have have found the Problem

/effect p night_vision 300

It happens only with 1 Letter as a Goal

**Comment by MonoAdrian23** [comment]
OK i have have found the Problem

/effect p night_vision 300

It happens only with 1 Letter as a Goal

This sends the Console Error

**Comment by smartcmd** [comment]
ok I found the bug
thanks you for your reply

**Comment by smartcmd** [comment]
I have fixed it.And we will update soon

**Comment by MonoAdrian23** [comment]
Thank You very much ♥️
