### ISSUE TITLE
Fawe cant load in PNX

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkitX/PowerNukkitX#314]
# 🔌 Plugin compatibility issue
 java.lang.NoSuchFieldException: modifiers

at java.base/java.lang.Class.getDeclaredField(Class.java:2610)

at com.boydti.fawe.config.Config.setAccessible(Config.java:451)

at com.boydti.fawe.config.Config.save(Config.java:288)

at com.boydti.fawe.config.Config.<init>(Config.java:27)

at com.boydti.fawe.config.Settings.<init>(Settings.java:8)

at com.boydti.fawe.config.Settings.<clinit>(Settings.java:10)

at com.boydti.fawe.nukkit.core.NukkitWorldEdit.onEnable(NukkitWorldEdit.java:79)

at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:105)

at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:120)

at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:463)

at cn.nukkit.Server.enablePlugin(Server.java:996)

at cn.nukkit.Server.enablePlugins(Server.java:985)

at cn.nukkit.Server.<init>(Server.java:823)

at cn.nukkit.Nukkit.main(Nukkit.java:209)

java.lang.NullPointerException: Cannot assign field "SHORTEN_URLS" because "com.boydti.fawe.config.Settings.IMP.WEB" is null

at com.boydti.fawe.nukkit.core.NukkitWorldEdit.onEnable(NukkitWorldEdit.java:79)

at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:105)

at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:120)

at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:463)

at cn.nukkit.Server.enablePlugin(Server.java:996)

at cn.nukkit.Server.enablePlugins(Server.java:985)

at cn.nukkit.Server.<init>(Server.java:823)

at cn.nukkit.Nukkit.main(Nukkit.java:209

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkitX version: (git-d512ab7)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment]
Is there a Version for it?

**Comment by CoolLoong** [comment]
> Is there a Version for it?

There is already a fork, but it has not been adapted yet

**Comment by Superice666** [comment]
try this https://github.com/PowerNukkitX/FastAsyncWorldEdit

**Comment by MonoAdrian23** [comment]
I have nothing to build for now

**Comment by MonoAdrian23** [comment]
Thanks
I Test this Plugin now.
