### ISSUE TITLE
 Cannot load from byte/boolean array because "this.skyLight" is null

### ISSUE THREAD

**Issue by CivicXFB** [PowerNukkitX/PowerNukkitX#427]
# 🐞 错误汇报

21:12:00 [FATAL] Exception in asynchronous task
java.lang.NullPointerException: Cannot load from byte/boolean array because "this.skyLight" is null
        at cn.nukkit.level.format.anvil.ChunkSection.setBlockSkyLight(ChunkSection.java:480) ~[PowerNukkitX-master-2779d4d56.jar:?]
        at cn.nukkit.level.format.generic.BaseChunk.setBlockSkyLight(BaseChunk.java:317) ~[PowerNukkitX-master-2779d4d56.jar:?]
        at cn.nukkit.level.format.generic.BaseFullChunk.populateSkyLight(BaseFullChunk.java:318) ~[PowerNukkitX-master-2779d4d56.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.generationTask(PopulationTask.java:116) ~[PowerNukkitX-master-2779d4d56.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:48) ~[PowerNukkitX-master-2779d4d56.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[PowerNukkitX-master-2779d4d56.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[PowerNukkitX-master-2779d4d56.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[PowerNukkitX-master-2779d4d56.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[PowerNukkitX-master-2779d4d56.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[PowerNukkitX-master-2779d4d56.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[PowerNukkitX-master-2779d4d56.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[PowerNukkitX-master-2779d4d56.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[PowerNukkitX-master-2779d4d56.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[PowerNukkitX-master-2779d4d56.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.onRun(PopulationTask.java:43) ~[PowerNukkitX-master-2779d4d56.jar:?]
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:26) ~[PowerNukkitX-master-2779d4d56.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by smartcmd** [comment]
天光计算错误

**Comment by Blackjack200** [comment]
装插件了吗，如果装了，删掉插件还会发生吗

**Comment by CivicXFB** [comment]
无

**Comment by CivicXFB** [comment]
装了tips 计分板api papi类型的变量

**Comment by CoolLoong** [comment]
#524
