### ISSUE TITLE
潜行放箱子无法打开变成幽灵方块

### ISSUE THREAD

**Issue by CivicXFB** [PowerNukkitX/PowerNukkitX#451]
### 📸 截图或视频

https://user-images.githubusercontent.com/61540722/178855913-1c65969d-efce-4beb-bc72-0c41b8e83c02.mp4

### ▶ 复现步骤

潜行在箱子上面放箱子

### ✔ 预期行为

能正常打开

### ❌ 实际行为

无法打开变成幽灵方块

### 💢 错误堆栈或崩溃日志

ERROR - nukkit.level.tickError
java.lang.ClassCastException: class cn.nukkit.lang.TextContainer cannot be cast to class cn.nukkit.lang.TranslationContainer (cn.nukkit.lang.TextContainer and cn.nukkit.lang.TranslationContainer are in unnamed module of loader 'app')
	at cn.nukkit.Player.kill(Player.java:5188) ~[powernukkitx.jar:?]
	at cn.nukkit.entity.Entity.setHealth(Entity.java:1522) ~[powernukkitx.jar:?]
	at cn.nukkit.entity.EntityLiving.setHealth(EntityLiving.java:85) ~[powernukkitx.jar:?]
	at cn.nukkit.Player.setHealth(Player.java:5325) ~[powernukkitx.jar:?]
	at cn.nukkit.entity.Entity.attack(Entity.java:1483) ~[powernukkitx.jar:?]
	at cn.nukkit.entity.EntityLiving.attack(EntityLiving.java:125) ~[powernukkitx.jar:?]
	at cn.nukkit.entity.EntityHumanType.attack(EntityHumanType.java:184) ~[powernukkitx.jar:?]
	at cn.nukkit.Player.attack(Player.java:5488) ~[powernukkitx.jar:?]
	at nukkitcoders.mobplugin.entities.monster.walking.Zombie.attackEntity(Zombie.java:99) ~[?:?]
	at nukkitcoders.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:162) ~[?:?]
	at cn.nukkit.level.Level.doTick(Level.java:1015) ~[powernukkitx.jar:?]
	at cn.nukkit.Server.checkTickUpdates(Server.java:1373) [powernukkitx.jar:?]
	at cn.nukkit.Server.tick(Server.java:1458) [powernukkitx.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1227) [powernukkitx.jar:?]
	at cn.nukkit.Server.start(Server.java:1187) [powernukkitx.jar:?]
	at cn.nukkit.Server.<init>(Server.java:852) [powernukkitx.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:212) [powernukkitx.jar:?]

### 💬 其他信息

 此服务器正在运行 Nukkit 1.6.0.0-PNX (git-c89df57) 「PowerNukkitX」API 版本 1.0.14 的 Minecraft: BE v1.19.10 (协议版本 534)
PowerNukkit v1.6.0.0-PNX, ScoreboardPlugin v1.0, MobPlugin v1.22.0, FakeInventories v1.0.3, World v1.0.6, TribeBE v1.0.0, EssentialsNK v1.9.2, KotlinLib v1.0, DbLib v1.0.1, FastAsyncWorldEdit vunknown

**Comment by Ootmnt150oO** [comment]
要不要試試先把Mobplugin移除看看

**Comment by smartcmd** [comment]
实测无法复现
