### ISSUE TITLE
放置生物出现报错

### ISSUE THREAD

**Issue by CivicXFB** [PowerNukkitX/PowerNukkitX#482]
# 🐞 错误汇报

没有安装任何插件情况下使用生物蛋生成生物会疯狂报错

### ✔ 预期行为

有报错

### ❌ 实际行为

无报错
### 💢 错误堆栈或崩溃日志

08:09:48 [ERROR] nukkit.level.tickError
java.lang.NullPointerException: Cannot invoke "cn.nukkit.entity.ai.behaviorgroup.IBehaviorGroup.tickRunningCoreBehaviors(cn.nukkit.entity.EntityIntelligent)" because "behaviorGroup" is null
        at cn.nukkit.entity.EntityIntelligent.onUpdate(EntityIntelligent.java:65) ~[PowerNukkitX-master-d0bbadbd4.jar:?]
        at cn.nukkit.level.Level.doTick(Level.java:1065) ~[PowerNukkitX-master-d0bbadbd4.jar:?]
        at cn.nukkit.Server.checkTickUpdates(Server.java:1381) [PowerNukkitX-master-d0bbadbd4.jar:?]
        at cn.nukkit.Server.tick(Server.java:1466) [PowerNukkitX-master-d0bbadbd4.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:1235) [PowerNukkitX-master-d0bbadbd4.jar:?]
        at cn.nukkit.Server.start(Server.java:1195) [PowerNukkitX-master-d0bbadbd4.jar:?]
        at cn.nukkit.Server.<init>(Server.java:856) [PowerNukkitX-master-d0bbadbd4.jar:?]

### 💬 其他信息

PowerNukkitX-master-d0bbadbd4.jar 无任何插件

**Comment by CivicXFB** [comment]
并且不生成生物
