### ISSUE TITLE
the plugin is looking for a place, and there is always 0

### ISSUE THREAD

**Issue by feanchy** [PowerNukkitX/PowerNukkitX#688]
"ForkJoinPool.commonPool-worker-22" daemon prio=5 Id=98 WAITING on java.util.concurrent.ForkJoinPool@7e366c6f
at java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method)
- waiting on java.util.concurrent.ForkJoinPool@7e366c6f
at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1724)
at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
at java.base@17.0.4.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

"ForkJoinPool.commonPool-worker-23" daemon prio=5 Id=99 WAITING on java.util.concurrent.ForkJoinPool@7e366c6f
at java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method)
- waiting on java.util.concurrent.ForkJoinPool@7e366c6f
at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1724)
at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
at java.base@17.0.4.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

"Nukkit Asynchronous Task Handler https://github.com/PowerNukkitX/PowerNukkitX/issues/21" daemon prio=5 Id=101 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@47224d5d
at java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method)
- waiting on java.util.concurrent.SynchronousQueue$TransferStack@47224d5d
at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack$SNode.block(SynchronousQueue.java:288) at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:397)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:886)
at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
...

"Nukkit Asynchronous Task Handler https://github.com/PowerNukkitX/PowerNukkitX/issues/23" daemon prio=5 Id=103 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@47224d5d
at java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method)
- waiting on java.util.concurrent.SynchronousQueue$TransferStack@47224d5d
at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack$SNode.block(SynchronousQueue.java:288) at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:397)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:886)
at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
...

"Nukkit Asynchronous Task Handler https://github.com/PowerNukkitX/PowerNukkitX/pull/24" daemon prio=5 Id=104 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@47224d5d
at java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method)
- waiting on java.util.concurrent.SynchronousQueue$TransferStack@47224d5d
at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack$SNode.block(SynchronousQueue.java:288) at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:397)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:886)
at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
...

"Nukkit Asynchronous Task Handler https://github.com/PowerNukkitX/PowerNukkitX/issues/25" daemon prio=5 Id=107 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@47224d5d
at java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method)
- waiting on java.util.concurrent.SynchronousQueue$TransferStack@47224d5d
at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack$SNode.block(SynchronousQueue.java:288) at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:397)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:886)
at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
...

"Nukkit Asynchronous Task Handler https://github.com/PowerNukkitX/PowerNukkitX/issues/25" daemon prio=5 Id=108 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@47224d5d
at java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method)
- waiting on java.util.concurrent.SynchronousQueue$TransferStack@47224d5d
at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack$SNode.block(SynchronousQueue.java:288) at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:397)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:886)
at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
...

"Nukkit Asynchronous Task Handler https://github.com/PowerNukkitX/PowerNukkitX/issues/25" daemon prio=5 Id=109 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@47224d5d
at java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method)
- waiting on java.util.concurrent.SynchronousQueue$TransferStack@47224d5d
at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack$SNode.block(SynchronousQueue.java:288) at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:397)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:886)
at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
...

"Nukkit Asynchronous Task Handler https://github.com/PowerNukkitX/PowerNukkitX/issues/25" daemon prio=5 Id=110 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@47224d5d
at java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method)
- waiting on java.util.concurrent.SynchronousQueue$TransferStack@47224d5d
at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack$SNode.block(SynchronousQueue.java:288) at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:397)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:886)
at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
...

"Nukkit Asynchronous Task Handler https://github.com/PowerNukkitX/PowerNukkitX/issues/25" daemon prio=5 Id=111 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@47224d5d
at java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method)
- waiting on java.util.concurrent.SynchronousQueue$TransferStack@47224d5d
at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack$SNode.block(SynchronousQueue.java:288) at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:397)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:886)
at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
...

"Nukkit Asynchronous Task Handler https://github.com/PowerNukkitX/PowerNukkitX/issues/25" daemon prio=5 Id=112 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@47224d5d
at java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method)
- waiting on java.util.concurrent.SynchronousQueue$TransferStack@47224d5d
at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack$SNode.block(SynchronousQueue.java:288) at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:397)
at java.base@17.0.4.1/java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:886)
at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
...

java.lang.StackOverflowError: null
at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.int2ObjectEntrySet(Int2ObjectOpenHashMap.java:55) ~[fastutil-core-8.5.4.jar:?]
at it.unimi.dsi.fastutil.ints.Int2ObjectMap.entrySet(Int2ObjectMap.java:126) ~[fastutil-core-8.5.4.jar:?]
at it.unimi.dsi.fastutil.ints.Int2ObjectMap.entrySet(Int2ObjectMap.java:35) ~[fastutil-core-8.5.4.jar:?]
at cn.nukkit.utils.collection.ConvertingMapWrapper.(ConvertingMapWrapper.java:51) ~[powernukkitx.jar:?]
at cn.nukkit.utils.collection.ConvertingMapWrapper.(ConvertingMapWrapper.java:60) ~[powernukkitx.jar:?]
at cn.nukkit.level.format.generic.BaseRegionLoader.(BaseRegionLoader.java:40) ~[powernukkitx.jar:?]
at cn.nukkit.level.format.anvil.RegionLoader.(RegionLoader.java:42) ~[powernukkitx.jar:?]
at cn.nukkit.level.format.anvil.Anvil.loadRegion(Anvil.java:387) ~[powernukkitx.jar:?]
at cn.nukkit.level.format.anvil.Anvil.loadChunk(Anvil.java:320) ~[powernukkitx.jar:?]
at cn.nukkit.level.format.generic.BaseLevelProvider.getChunk(BaseLevelProvider.java:451) ~[powernukkitx.jar:?]
at cn.nukkit.level.Level.forceLoadChunk(Level.java:3978) ~[powernukkitx.jar:?]
at cn.nukkit.level.Level.getChunk(Level.java:3635) ~[powernukkitx.jar:?]
at cn.nukkit.level.Level.getHeightMap(Level.java:3615) ~[powernukkitx.jar:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:60) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]
at me.iwareq.rtp.Rtp.findRandomPosition(Rtp.java:64) ~[?:?]

**Comment by CoolLoong** [comment]
Hello, is there a source code for this plugin?

**Comment by feanchy** [comment]
> Привет, есть исходный код этого плагина?

yep

**Comment by CoolLoong** [comment]
https://gist.github.com/CoolLoong/c73ff0ced2de77d60c4cf7c6a6ddcf33#file-gistfile1-txt-L23

**Comment by feanchy** [comment]
> https://gist.github.com/CoolLoong/c73ff0ced2de77d60c4cf7c6a6ddcf33#file-gistfile1-txt-L23

![ывфвыыыыыыыыыыы](https://user-images.githubusercontent.com/50043944/194918373-05a54e98-9ad3-4f6b-8da0-f324a01cfd83.png)
