### ISSUE TITLE
When calling close() or kick() on a Player object inside of a PlayerQuitEvent, a java.lang.NullPointerException is raised on the method cn.nukkit.Player.resetCraftingGridType

### ISSUE THREAD

**Issue by KayllonDouglas** [PowerNukkitX/PowerNukkitX#743]
> If you call any of those methods when the player is quitting, another "ClosePlayer" is put on the network queue, and when the Network interface starts processing the queue, it try to close the player object that was already closed, and the cn.nukkit.Player.resetCraftingGridType() method try to add a item into the player inventory, but the inventory object is NULL because the player has already been closed;

```
Stack Trace:
02:04:17 [FATAL] nukkit.server.networkError
java.lang.NullPointerException: Cannot invoke "cn.nukkit.inventory.PlayerInventory.addItem(cn.nukkit.item.Item[])" because "this.inventory" is null
        at cn.nukkit.Player.resetCraftingGridType(Player.java:6244) ~[powernukkitx.jar:?]
        at cn.nukkit.Player.close(Player.java:5018) ~[powernukkitx.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:91) ~[powernukkitx.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:194) [powernukkitx.jar:?]
        at cn.nukkit.Server.tick(Server.java:1500) [powernukkitx.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:1279) [powernukkitx.jar:?]
        at cn.nukkit.Server.start(Server.java:1239) [powernukkitx.jar:?]
        at cn.nukkit.Server.<init>(Server.java:894) [powernukkitx.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:212) [powernukkitx.jar:?]
```

**Comment by CoolLoong** [comment]
Give the code,

**Comment by KayllonDouglas** [comment]
- Kicking:

![Screenshot_2022-10-25-23-07-31-429-edit_com termux](https://user-images.githubusercontent.com/76278156/197927172-79b14c91-c11f-4de7-adab-f480e5f4305d.jpg)

- Closing:

![Screenshot_2022-10-25-22-41-16-762-edit_com termux](https://user-images.githubusercontent.com/76278156/197927174-ce92c862-b6fe-4edf-b482-be5cde66486b.jpg)

**Comment by CoolLoong** [comment]
You should not use the close method on the playerquitevent, it will have no effect.If you want to set the quit message,use `setQuitMessage`.
