### ISSUE TITLE
在处理世界时间时NPE

### ISSUE THREAD

**Issue by Superice666** [PowerNukkitX/PowerNukkitX#804]
# 🐞 错误汇报
```
21:52:05 [ERROR] nukkit.level.tickError
java.lang.NullPointerException: Cannot invoke "cn.nukkit.level.GameRules.getBoolean(cn.nukkit.level.GameRule)" because "this.gameRules" is null
        at cn.nukkit.level.Level.checkTime(Level.java:1125) ~[powernukkitx.jar:?]
        at cn.nukkit.level.Level.doTick(Level.java:1161) ~[powernukkitx.jar:?]
        at cn.nukkit.Server.checkTickUpdates(Server.java:1425) [powernukkitx.jar:?]
        at cn.nukkit.Server.tick(Server.java:1511) [powernukkitx.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:1279) [powernukkitx.jar:?]
        at cn.nukkit.Server.start(Server.java:1239) [powernukkitx.jar:?]
        at cn.nukkit.Server.<init>(Server.java:894) [powernukkitx.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:160) [powernukkitx.jar:?]
```

**Comment by CoolLoong** [comment]
未知原因level.dat里面的GameRules没有填充

**Comment by CoolLoong** [comment]
版本问题

**Comment by CoolLoong** [comment]
那个用户没有更新最新版本PNX
