### ISSUE TITLE
原版NK地图加载发生严重错误

### ISSUE THREAD

**Issue by CivicXFB** [PowerNukkitX/PowerNukkitX#814]
# 🐞 错误汇报
20:46:50 [FATAL] Exception in asynchronous task,Thread:Nukkit Asynchronous Task Handler #7
java.lang.IllegalArgumentException: Unable to set block runtime ID: 5753, palette: [6692, 655, 4692, 7701, 4363, 4291, 914, 4289, 7349, 5753]
        at cn.nukkit.level.util.PalettedBlockStorage.setBlock(PalettedBlockStorage.java:62) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.format.anvil.util.BlockStorage.setBlockState(BlockStorage.java:223) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.format.anvil.util.BlockStorage.getAndSetBlockState(BlockStorage.java:151) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.format.anvil.ChunkSection.getAndSetBlockState(ChunkSection.java:508) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.format.anvil.ChunkSection.setBlockStateAtLayer(ChunkSection.java:539) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.format.generic.BaseChunk.setBlockStateAtLayer(BaseChunk.java:218) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.format.generic.BaseChunk.setBlockAtLayer(BaseChunk.java:208) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.generator.SimpleChunkManager.setBlockAtLayer(SimpleChunkManager.java:75) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.generator.SimpleChunkManager.setBlockAt(SimpleChunkManager.java:65) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.generator.object.ore.OreType.spawn(OreType.java:92) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.generator.populator.impl.PopulatorOre.populate(PopulatorOre.java:57) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.generator.Normal.populateChunk(Normal.java:397) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.generationTask(PopulationTask.java:112) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:48) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.generator.task.PopulationTask.onRun(PopulationTask.java:43) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:26) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.IllegalArgumentException: Max value: 7. Received value [9]
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:303) ~[guava-30.1.1-jre.jar:?]
        at cn.nukkit.level.util.PaddedBitArray.set(PaddedBitArray.java:39) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.util.PalettedBlockStorage.setBlock(PalettedBlockStorage.java:60) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        ... 30 more
20:46:50 [ERROR] nukkit.level.tickError
java.lang.IllegalArgumentException: Unable to set block runtime ID: 7349, palette: [6692, 655, 4692, 7701, 4363, 4291, 914, 4289, 7349, 5753]
        at cn.nukkit.level.util.PalettedBlockStorage.setBlock(PalettedBlockStorage.java:62) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.format.anvil.util.BlockStorage.writeObfuscatedTo(BlockStorage.java:543) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.format.anvil.SingleLayerStorage.writeObfuscatedTo(SingleLayerStorage.java:157) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.format.anvil.ChunkSection.writeObfuscatedTo(ChunkSection.java:723) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.format.anvil.Anvil.lambda$serialize$4(Anvil.java:284) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204) ~[?:?]
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[?:?]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.helpComplete(ForkJoinPool.java:1223) ~[?:?]
        at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1915) ~[?:?]
        at java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:433) ~[?:?]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:687) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateParallel(ForEachOps.java:188) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?]
        at java.util.stream.IntPipeline.forEach(IntPipeline.java:463) ~[?:?]
        at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:620) ~[?:?]
        at cn.nukkit.level.format.anvil.Anvil.serialize(Anvil.java:284) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.format.anvil.Anvil.requestChunkTask(Anvil.java:248) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.Level.processChunkRequest(Level.java:3823) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.Level.doTick(Level.java:1358) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.Server.checkTickUpdates(Server.java:1450) [PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.Server.tick(Server.java:1536) [PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:1304) [PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.Server.start(Server.java:1264) [PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.Server.<init>(Server.java:914) [PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:160) [PowerNukkitX-master-0d14c11d1.jar:?]
Caused by: java.lang.IllegalArgumentException: Max value: 7. Received value [8]
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:303) ~[guava-30.1.1-jre.jar:?]
        at cn.nukkit.level.util.PaddedBitArray.set(PaddedBitArray.java:39) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        at cn.nukkit.level.util.PalettedBlockStorage.setBlock(PalettedBlockStorage.java:60) ~[PowerNukkitX-master-0d14c11d1.jar:?]
        ... 30 more

### 💬 其他信息
服务器运行版本
此服务器正在运行 Nukkit 1.19.40-r3 (git-0d14c11d1) 版本 "PowerNukkitX" (API 1.0.14)

**Comment by CoolLoong** [comment]
转换器转出来的地图吧

**Comment by CivicXFB** [comment]
是的

**Comment by CivicXFB** [comment]
在它外围是nk原版地图跑图会出现这个错误
