### ISSUE TITLE
用我自己开发的插件时出现的诡异异常

### ISSUE THREAD

**Issue by Xinsheng1687** [PowerNukkitX/PowerNukkitX#816]
# 🐞 错误汇报

我是插件作者，编写了一个不小的插件，用到了mysql（jdbc），druid。用我的插件时服务端可以启动，玩家进游戏会触发一个报错。然后服务端就停止运行了。报错如下：
```
"main" prio=5 Id=1 RUNNABLE
      at java.management@17.0.5/sun.management.ThreadImpl.dumpThreads0(Native Method)
      at java.management@17.0.5/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:521)
      at java.management@17.0.5/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:509)
      at app//cn.nukkit.utils.Utils.getAllThreadDumps(Utils.java:174)
      at app//cn.nukkit.Server.tickProcessor(Server.java:1309)
      at app//cn.nukkit.Server.start(Server.java:1238)
      at app//cn.nukkit.Server.<init>(Server.java:893)
      at app//cn.nukkit.Nukkit.main(Nukkit.java:160)


"Reference Handler" daemon prio=10 Id=2 RUNNABLE
      at java.base@17.0.5/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
      at java.base@17.0.5/java.lang.ref.Reference.processPendingReferences(Reference.java:253)
      at java.base@17.0.5/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)


"Finalizer" daemon prio=8 Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@5aa5b3af
      at java.base@17.0.5/java.lang.Object.wait(Native Method)
      -  waiting on java.lang.ref.ReferenceQueue$Lock@5aa5b3af
      at java.base@17.0.5/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
      at java.base@17.0.5/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
      at java.base@17.0.5/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:172)


"Signal Dispatcher" daemon prio=9 Id=4 RUNNABLE


"Attach Listener" daemon prio=5 Id=5 RUNNABLE


"Common-Cleaner" daemon prio=8 Id=11 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@344cf00f
      at java.base@17.0.5/java.lang.Object.wait(Native Method)
      -  waiting on java.lang.ref.ReferenceQueue$Lock@344cf00f
      at java.base@17.0.5/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
      at java.base@17.0.5/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
      at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
      at java.base@17.0.5/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)


"Notification Thread" daemon prio=9 Id=12 RUNNABLE


"WindowsStreamPump" daemon prio=5 Id=17 RUNNABLE (in native)
      at app//com.sun.jna.Native.invokeInt(Native Method)
      at app//com.sun.jna.Function.invoke(Function.java:426)
      at app//com.sun.jna.Function.invoke(Function.java:361)
      at app//com.sun.jna.Library$Handler.invoke(Library.java:265)
      at app//org.jline.terminal.impl.jna.win.$Proxy27.WaitForSingleObject(Unknown Source)
      at app//org.jline.terminal.impl.jna.win.JnaWinSysTerminal.readConsoleInput(JnaWinSysTerminal.java:207)
      at app//org.jline.terminal.impl.jna.win.JnaWinSysTerminal.processConsoleInput(JnaWinSysTerminal.java:130)
      at app//org.jline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:460)
      ...


"Thread-0" prio=5 Id=21 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@598ff2b3
      at java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method)
      -  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@598ff2b3
      at java.base@17.0.5/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
      at java.base@17.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1757)
      at app//org.jline.utils.NonBlockingPumpReader.read(NonBlockingPumpReader.java:78)
      at app//org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57)
      at app//org.jline.keymap.BindingReader.readCharacter(BindingReader.java:160)
      at app//org.jline.keymap.BindingReader.readBinding(BindingReader.java:110)
      at app//org.jline.keymap.BindingReader.readBinding(BindingReader.java:61)
      ...


"pool-5-thread-1" prio=5 Id=23 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1002f859
      at java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method)
      -  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1002f859
      at java.base@17.0.5/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
      at java.base@17.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
      at java.base@17.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
      at java.base@17.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
      at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
      at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
      at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
      ...


"pool-6-thread-1" prio=5 Id=24 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@67cd193d
      at java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method)
      -  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@67cd193d
      at java.base@17.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
      at java.base@17.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
      at java.base@17.0.5/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
      at java.base@17.0.5/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
      at java.base@17.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623)
      at java.base@17.0.5/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
      at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
      ...


"Network Listener - #0" daemon prio=5 Id=25 RUNNABLE
      at java.base@17.0.5/sun.nio.ch.WEPoll.wait(Native Method)
      at java.base@17.0.5/sun.nio.ch.WEPollSelectorImpl.doSelect(WEPollSelectorImpl.java:111)
      at java.base@17.0.5/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
      -  locked io.netty.channel.nio.SelectedSelectionKeySet@34525143
      -  locked sun.nio.ch.WEPollSelectorImpl@126e2710
      at java.base@17.0.5/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:141)
      at app//io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
      at app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:817)
      at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
      at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
      ...


"Network Listener - #1" daemon prio=5 Id=26 RUNNABLE
      at java.base@17.0.5/sun.nio.ch.WEPoll.wait(Native Method)
      at java.base@17.0.5/sun.nio.ch.WEPollSelectorImpl.doSelect(WEPollSelectorImpl.java:111)
      at java.base@17.0.5/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
      -  locked io.netty.channel.nio.SelectedSelectionKeySet@1529d534
      -  locked sun.nio.ch.WEPollSelectorImpl@1a22325d
      at java.base@17.0.5/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:141)
      at app//io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
      at app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:817)
      at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
      at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
      ...


"BlackBE-API-Connection-Thread" prio=5 Id=27 WAITING
      at java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method)
      at java.base@17.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
      at xyz.blackbe.blackbeplugin.runnable.AsyncTaskWorker.run(AsyncTaskWorker.java:24)


"mysql-cj-abandoned-connection-cleanup" daemon prio=5 Id=29 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@3c5cb013
      at java.base@17.0.5/java.lang.Object.wait(Native Method)
      -  waiting on java.lang.ref.ReferenceQueue$Lock@3c5cb013
      at java.base@17.0.5/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
      at com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:91)
      at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
      at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
      at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)

      Number of locked synchronizers = 1
      - java.util.concurrent.ThreadPoolExecutor$Worker@522f0bb8


"Druid-ConnectionPool-Create-574999722" daemon prio=5 Id=30 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@5f69462f
      at java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method)
      -  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@5f69462f
      at java.base@17.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
      at java.base@17.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
      at java.base@17.0.5/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
      at java.base@17.0.5/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
      at java.base@17.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623)
      at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2852)


"Druid-ConnectionPool-Destroy-574999722" daemon prio=5 Id=31 TIMED_WAITING
      at java.base@17.0.5/java.lang.Thread.sleep(Native Method)
      at com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:2951)


"Thread-4" prio=5 Id=32 TIMED_WAITING
      at java.base@17.0.5/java.lang.Thread.sleep(Native Method)
      at top.nlos.Xinsheng.GameManager.Matcher.lambda$matching$0(Matcher.java:34)
      at top.nlos.Xinsheng.GameManager.Matcher$$Lambda$530/0x00000007c099a200.run(Unknown Source)
      at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)


"Watchdog" daemon prio=1 Id=33 TIMED_WAITING
      at java.base@17.0.5/java.lang.Thread.sleep(Native Method)
      at app//cn.nukkit.utils.Watchdog.run(Watchdog.java:97)


"Nukkit Asynchronous Task Handler #0" daemon prio=5 Id=35 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@432b883
      at java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method)
      -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@432b883
      at java.base@17.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
      at java.base@17.0.5/java.util.concurrent.SynchronousQueue$TransferStack$SNode.block(SynchronousQueue.java:288)
      at java.base@17.0.5/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
      at java.base@17.0.5/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
      at java.base@17.0.5/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:397)
      at java.base@17.0.5/java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:886)
      at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
      ...


"Nukkit Asynchronous Task Handler #1" daemon prio=5 Id=57 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@432b883
      at java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method)
      -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@432b883
      at java.base@17.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
      at java.base@17.0.5/java.util.concurrent.SynchronousQueue$TransferStack$SNode.block(SynchronousQueue.java:288)
      at java.base@17.0.5/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
      at java.base@17.0.5/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
      at java.base@17.0.5/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:397)
      at java.base@17.0.5/java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:886)
      at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
      ...


"Nukkit Asynchronous Task Handler #2" daemon prio=5 Id=58 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@432b883
      at java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method)
      -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@432b883
      at java.base@17.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
      at java.base@17.0.5/java.util.concurrent.SynchronousQueue$TransferStack$SNode.block(SynchronousQueue.java:288)
      at java.base@17.0.5/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
      at java.base@17.0.5/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
      at java.base@17.0.5/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:397)
      at java.base@17.0.5/java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:886)
      at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
      ...


"pool-9-thread-1" prio=5 Id=59 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@f09c282
      at java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method)
      -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@f09c282
      at java.base@17.0.5/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
      at java.base@17.0.5/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401)
      at java.base@17.0.5/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903)
      at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061)
      at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
      at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
      at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)


"pool-9-thread-2" prio=5 Id=60 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@f09c282
      at java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method)
      -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@f09c282
      at java.base@17.0.5/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
      at java.base@17.0.5/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401)
      at java.base@17.0.5/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903)
      at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061)
      at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
      at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
      at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)


"pool-9-thread-3" prio=5 Id=61 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@f09c282
      at java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method)
      -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@f09c282
      at java.base@17.0.5/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
      at java.base@17.0.5/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401)
      at java.base@17.0.5/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903)
      at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061)
      at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
      at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
      at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)


"ForkJoinPool-1-worker-1" daemon prio=5 Id=62 WAITING on java.util.concurrent.ForkJoinPool@560c3758
      at java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method)
      -  waiting on java.util.concurrent.ForkJoinPool@560c3758
      at java.base@17.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
      at java.base@17.0.5/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1724)
      at java.base@17.0.5/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
      at java.base@17.0.5/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


"ForkJoinPool.commonPool-worker-1" daemon prio=5 Id=63 TIMED_WAITING on java.util.concurrent.ForkJoinPool@43414b88
      at java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method)
      -  waiting on java.util.concurrent.ForkJoinPool@43414b88
      at java.base@17.0.5/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:410)
      at java.base@17.0.5/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1726)
      at java.base@17.0.5/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
      at java.base@17.0.5/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


"ForkJoinPool-1-worker-2" daemon prio=5 Id=64 TIMED_WAITING on java.util.concurrent.ForkJoinPool@560c3758
      at java.base@17.0.5/jdk.internal.misc.Unsafe.park(Native Method)
      -  waiting on java.util.concurrent.ForkJoinPool@560c3758
      at java.base@17.0.5/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:410)
      at java.base@17.0.5/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1726)
      at java.base@17.0.5/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623)
      at java.base@17.0.5/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


java.lang.IncompatibleClassChangeError: Expecting non-static method 'void top.nlos.Xinsheng.Safety.Safety.onPlayerJoin(cn.nukkit.event.player.PlayerJoinEvent)'
      at cn.nukkit.plugin.PNXMethodEventExecutor$12.execute(EventHandler@top.nlos.Xinsheng.Safety.Safety#onPlayerJoin) ~[?:?]
      at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:61) ~[PowerNukkitX-master-3259e990d.jar:?]
      at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:582) ~[PowerNukkitX-master-3259e990d.jar:?]
      at cn.nukkit.Player.doFirstSpawn(Player.java:743) ~[PowerNukkitX-master-3259e990d.jar:?]
      at cn.nukkit.Player.sendNextChunk(Player.java:683) ~[PowerNukkitX-master-3259e990d.jar:?]
      at cn.nukkit.Player.checkNetwork(Player.java:3185) ~[PowerNukkitX-master-3259e990d.jar:?]
      at cn.nukkit.Server.tick(Server.java:1513) ~[PowerNukkitX-master-3259e990d.jar:?]
      at cn.nukkit.Server.tickProcessor(Server.java:1278) [PowerNukkitX-master-3259e990d.jar:?]
      at cn.nukkit.Server.start(Server.java:1238) [PowerNukkitX-master-3259e990d.jar:?]
      at cn.nukkit.Server.<init>(Server.java:893) [PowerNukkitX-master-3259e990d.jar:?]
      at cn.nukkit.Nukkit.main(Nukkit.java:160) [PowerNukkitX-master-3259e990d.jar:?]
2022-11-29 11:59:24.949 [main] INFO  - §eXinsheng1687 退出了游戏
2022-11-29 11:59:24.951 [main] INFO  - §bXinsheng1687§f[/45.116.152.48:48950] 登出游戏，原因：服务器已停止运行，详情请资讯管理员
2022-11-29 11:59:24.951 [main] INFO  - 关闭 NLOS_Core v0.1 中
2022-11-29 11:59:24.951 [main] INFO  - [NLOS_Core]: --------------------NLOS_Core已关闭--------------------
2022-11-29 11:59:24.962 [main] INFO  - 关闭 BlackBE v1.3.1 中
2022-11-29 11:59:24.962 [main] INFO  - 正在卸载世界 "§aworld§f"
2022-11-29 11:59:25.036 [main] INFO  - Stopping other threads
```
NLOS_Core就是我的插件，这个报错真的很长，而且和普通的runtime exception看起来还不一样。我不明白。
希望有人能够帮忙解答一下谢谢
我该怎么做，或者是什么引起的，或者是可能由什么引起的。
如果想和我交流，我在qq群里，新生就是我，可以直接找我。
多谢了。

**Comment by Mcayear** [comment]
6

**Comment by Xinsheng1687** [comment]
> 6
请问你知道是什么原因吗

**Comment by Superice666** [comment]
静态函数作事件监听器会使得JVM崩溃
