### ISSUE TITLE
可能无法正确从旁观者模式切换到其它游戏模式

### ISSUE THREAD

**Issue by Silvigarabis** [PowerNukkitX/PowerNukkitX#939]
# 🐞 错误汇报

某种情况下，无法正确从旁观者模式切换到其他的游戏模式。  
在切换到旁观者模式之后退出服务器，再次进入后：
- 如果切换到创造模式，会发现创造物品栏为空。
- 如果切换到生存模式，会发现无法显示任何合成配方。
- 冒险模式未测试。

即使反复切换游戏模式也无济于事，必须重新进入服务器，才能恢复生存或创造的正常状态。

### 📸 截图或视频
（无）

### ▶ 复现步骤
1.进入服务器。
2.将游戏模式切换为旁观模式。
3.退出服务器。
4.再次进入服务器。
5.将游戏模式切换为生存或创造模式。
6.打开物品栏查看情况，没有显示任何合成配方或显示任何创造模式可以直接获取的物品。

### ✔ 预期行为
从旁观者模式切换到生存或创造模式后，物品栏应该显示合成配方或可获得的物品。

### ❌ 实际行为
从旁观者模式离开后，物品栏只显示已经拥有的物品，未显示合成配方或可获得的物品。

### 📋 Debug information
服务器版本（使用 `/version` 获取）：`此服务器正在运行 Nukkit 1.19.50-r3 (git-e8ef67a91) 「
PowerNukkitX」API 版本 1.0.14 的 Minecraft: BE v1.19.50 (协议版本 560)>`
查看时序报告：<https://timings.aikar.co/dev/?id=00c58b62d93e47219eddef5aee0f6b98>
抱歉，我在运行命令 `debugpaste upload` 时出现了错误，上传失败。如果确实需要，我将其上传到了 Mediafire，可以在 [这里](https://www.mediafire.com/file/gloi158sl98ibgb/debugpaste-2023-01-12T21.37.50.185%252B0800.zip/file) 找到它。
```
21:37:50 [INFO ] The /debugpaste is executing, please wait...
21:37:50 [INFO ] A debug paste was created at debugpastes/debugpaste-2023-01-12T21.37.50.185+0800.zip
21:37:50 [INFO ] Uploading...
21:37:51 [ERROR] Failed to upload the debugpaste /imeaces/server/test_pnx/debugpastes/debugpaste-2023-01-12T21.37.50.185+0800.zip
java.io.IOException: The server responded with code 500, expected 201
        at cn.nukkit.command.defaults.DebugPasteCommand.upload(DebugPasteCommand.java:164) [PowerNukkitX-master-e8ef67a91.jar:?]
        at cn.nukkit.command.defaults.DebugPasteCommand$1.onRun(DebugPasteCommand.java:345) [PowerNukkitX-master-e8ef67a91.jar:?]
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:26) [PowerNukkitX-master-e8ef67a91.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
21:37:51 [INFO ] Failed to upload the debugpaste, the file is still available in your server directory.
```

### 💢 错误堆栈或崩溃日志
服务器没有崩溃，且控制台没有输出错误消息。

### 💬 其他信息
1.我在 BDS 服务器上也进行了类似的测试，从旁观者模式切换到其他模式并没有出现上述问题。
2.测试使用的游戏版本为 `1.19.50`。

**Comment by CoolLoong** [comment]
请问你是否使用了Waterdog代理

**Comment by Silvigarabis** [comment]
没有。

**Comment by Silvigarabis** [comment]
没有。

**Comment by smartcmd** [comment]
已尝试修复
