### ISSUE TITLE
无法识别装备

### ISSUE THREAD

**Issue by CivicXFB** [PowerNukkitX/PowerNukkitX#979]
# 🐞 错误汇报
ERROR - An error occurred whilst handling InventoryTransactionPacket for xwz1110
java.lang.RuntimeException: Output list is full can't add Item Netherite Sword (743:0)x1
	at cn.nukkit.inventory.transaction.CraftingTransaction.setExtraOutput(CraftingTransaction.java:91) ~[PowerNukkitX-master-c66547408.jar:?]
	at cn.nukkit.inventory.transaction.action.CraftingTransferMaterialAction.onAddToTransaction(CraftingTransferMaterialAction.java:29) ~[PowerNukkitX-master-c66547408.jar:?]
	at cn.nukkit.inventory.transaction.InventoryTransaction.addAction(InventoryTransaction.java:103) ~[PowerNukkitX-master-c66547408.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:4798) ~[PowerNukkitX-master-c66547408.jar:?]
	at cn.nukkit.network.session.RakNetPlayerSession.serverTick(RakNetPlayerSession.java:180) [PowerNukkitX-master-c66547408.jar:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:95) [PowerNukkitX-master-c66547408.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:233) [PowerNukkitX-master-c66547408.jar:?]
	at cn.nukkit.Server.tick(Server.java:1702) [PowerNukkitX-master-c66547408.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:1432) [PowerNukkitX-master-c66547408.jar:?]
	at cn.nukkit.Server.start(Server.java:1392) [PowerNukkitX-master-c66547408.jar:?]
	at cn.nukkit.Server.<init>(Server.java:938) [PowerNukkitX-master-c66547408.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:160) [PowerNukkitX-master-c66547408.jar:?]
我认为可能是玩家使用修改器修改对应附魔值导致核心不识别其次这个报错可以让服务器停止运行希望能修复
### ▶ 复现步骤
在运行时触发我查找相对应插件只有于背包类的只有INVSEE

### ✔ 预期行为
不会发生错误

### ❌ 实际行为
发生错误

### 💬 其他信息
版本: 1.19.50
分支: PowerNukkitX-master-c66547408

**Comment by CivicXFB** [comment]
[server.log](https://github.com/PowerNukkitX/PowerNukkitX/files/10526158/server.log)
