### ISSUE TITLE
无法加载pnx-js插件

### ISSUE THREAD

**Issue by Mcayear** [PowerNukkitX/PowerNukkitX#993]
# 🐞 错误汇报

插件本身可以正常加载，下面只是举例。
```
2023-02-02 12:22:45.653 [main] INFO  - 读取 LiteLoaderLibs v0.0.3 中
2023-02-02 12:22:45.662 [main] FATAL - Could not load plugin
java.lang.IllegalArgumentException: Could not find option with name js.esm-eval-returns-exports.
	at com.oracle.truffle.polyglot.PolyglotEngineException.illegalArgument(PolyglotEngineException.java:131) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.polyglot.OptionValuesImpl.failNotFound(OptionValuesImpl.java:274) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.parseOptions(PolyglotEngineImpl.java:726) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:307) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.polyglot.PolyglotImpl.buildEngine(PolyglotImpl.java:288) ~[org.graalvm.truffle:?]
	at org.graalvm.polyglot.Engine$Builder.build(Engine.java:625) ~[org.graalvm.sdk:?]
	at org.graalvm.polyglot.Context$Builder.build(Context.java:1827) ~[org.graalvm.sdk:?]
	at cn.nukkit.plugin.CommonJSPlugin.init(CommonJSPlugin.java:95) ~[PowerNukkitX-master-0b14a04aa.jar:?]
	at cn.nukkit.plugin.JSPluginLoader.loadPlugin(JSPluginLoader.java:39) ~[PowerNukkitX-master-0b14a04aa.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:126) [PowerNukkitX-master-0b14a04aa.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:315) [PowerNukkitX-master-0b14a04aa.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:163) [PowerNukkitX-master-0b14a04aa.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:155) [PowerNukkitX-master-0b14a04aa.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:151) [PowerNukkitX-master-0b14a04aa.jar:?]
	at cn.nukkit.Server.<init>(Server.java:842) [PowerNukkitX-master-0b14a04aa.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:160) [PowerNukkitX-master-0b14a04aa.jar:?]
2023-02-02 12:22:45.664 [main] FATAL - 无法读取插件 "LiteLoaderLibs"
2023-02-02 12:22:45.666 [main] INFO  - 读取 NPCDialog v0.0.1 中
2023-02-02 12:22:45.676 [main] FATAL - Could not load plugin
java.lang.IllegalArgumentException: Could not find option with name js.esm-eval-returns-exports.
	at com.oracle.truffle.polyglot.PolyglotEngineException.illegalArgument(PolyglotEngineException.java:131) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.polyglot.OptionValuesImpl.failNotFound(OptionValuesImpl.java:274) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.parseOptions(PolyglotEngineImpl.java:726) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:307) ~[org.graalvm.truffle:?]
	at com.oracle.truffle.polyglot.PolyglotImpl.buildEngine(PolyglotImpl.java:288) ~[org.graalvm.truffle:?]
	at org.graalvm.polyglot.Engine$Builder.build(Engine.java:625) ~[org.graalvm.sdk:?]
	at org.graalvm.polyglot.Context$Builder.build(Context.java:1827) ~[org.graalvm.sdk:?]
	at cn.nukkit.plugin.CommonJSPlugin.init(CommonJSPlugin.java:95) ~[PowerNukkitX-master-0b14a04aa.jar:?]
	at cn.nukkit.plugin.JSPluginLoader.loadPlugin(JSPluginLoader.java:39) ~[PowerNukkitX-master-0b14a04aa.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:126) [PowerNukkitX-master-0b14a04aa.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:315) [PowerNukkitX-master-0b14a04aa.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:163) [PowerNukkitX-master-0b14a04aa.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:155) [PowerNukkitX-master-0b14a04aa.jar:?]
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:151) [PowerNukkitX-master-0b14a04aa.jar:?]
	at cn.nukkit.Server.<init>(Server.java:842) [PowerNukkitX-master-0b14a04aa.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:160) [PowerNukkitX-master-0b14a04aa.jar:?]
2023-02-02 12:22:45.679 [main] FATAL - 无法读取插件 "NPCDialog"
```

### 📸 截图或视频
```
此服务器正在运行 Nukkit 1.19.50-r3 (git-0b14a04aa) 「PowerNukkitX」API 版本 1.0.14 的 Minecraft: BE v1.19.50 (协议版本 560)
```
![image](https://user-images.githubusercontent.com/48203962/216328508-85a0f028-d830-4c4e-a35d-261868312f19.png)

```
> uname -a
Linux C20230108212716 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Mcayear** [comment]
原因是graalvm在最新版本中分离了graaljs

使用下面的命令可以快速在linux(ubuntu)系统上启动pnx，脚本会自动补全graaljs。
```shell
curl -O https://res.nullatom.com/file/pnx/cli/start.sh -L && chmod +x start.sh && ./start.sh
```
